### ISSUE TITLE
Please publish AppImage

### ISSUE THREAD

**Issue by probonopd** [eugenemel/maven#10]
Please publish the AppImage on GitHub Releases, thanks.

**Comment by lparsons** [comment]
That's the plan. Just awaiting a few final tweaks and the new version will be ready to go. Ping @eugenemel

**Comment by lparsons** [comment]
The AppImage for version 8.0.0 is now up on the [GitHub releases page](https://github.com/eugenemel/maven/releases). Enjoy, and please let us know if you encounter issues, etc.

Closed by commit b7653a8a071aa847746aec4e1bf342938efe03f4.

**Comment by probonopd** [comment]
Thank you very much. Can you please run your desktop file through `desktop-file-validate` and make sure it passes?

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/270095294#L594-L595

**Comment by lparsons** [comment]
@probonopd Here is my attempt to fix the issue (https://github.com/lparsons/maven/commit/3579eaca714bc221ff1d4c21dd77b7a949485794). Can you review and let me know if that looks correct? `desktop-file-validate` likes the file, but I'm new to Linux packaging so I'm not sure if there is a better way.

**Comment by probonopd** [comment]
Thanks @lparsons. Still doesn't pass for me, https://travis-ci.org/AppImage/appimage.github.io/builds/270498863#L594

Can you make the icon entry in the desktop file `Icon=maven` (without a path and without a suffix), and use `maven.png` as the filename for your icon, and retry please? Thanks.

**Comment by lparsons** [comment]
@probonopd Sorry, there is no updated AppImage yet, I don't want to merge these changes if they aren't right. I just pointed to the commit so you can see the changes. Basically, I had to make a copy of the icon file (`icon.png`) one directory up (not in `images`) and change the desktop icon entry to `Icon=icon`. This still works on my side, and passes the validation. Just wanted to be sure that is how it should be done.

**Comment by probonopd** [comment]
Ah ok, I see. Unfortiunately my test automation setup can only test AppImages once they are uploaded...

**Comment by lparsons** [comment]
@probonopd No problem, I'll go ahead and push this update then. Might be a little bit, since I'd like to roll in a few fixes before the next release.

**Comment by probonopd** [comment]
Sure, no hurries.
