### ISSUE TITLE
Maven crashed when I tried to export "peak detector" list

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#101]
I tried to export the csv file of the "peak detector", which is the least of all features. However, Maven crashed multiple times and I still haven't able to do that.

**Comment by PMSeitzer** [comment]
OK. Can you provide a reproducible example? Include files, settings, and instructions.

**Comment by ngoccalico** [comment]
I will share with you my mzrollDB file via google drive. All I did was opening the file and try to export out the "detected features" as the csv or tab, then Maven crashed.

**Comment by PMSeitzer** [comment]
To reproduce:

1. open mzrollDB

2. clear clusters

3. .export everything from `peakdetector` table

segmentation fault

**Comment by PMSeitzer** [comment]
Implemented as of 198ce03df2c4f41aa3f05d49b6a030b334bce5f7
