### ISSUE TITLE
Intuitive Zooming on EIC Peaks

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#104]
EIC pane in Maven locks the Yaxis to the max peak height of the selected peak group, making it effectively impossible to zoom in on small side peaks that are being picked up as the same peak group. This can be toggled off by unselecting "Group Peaks" as a right-click option on the EIC pane and then manually integrating peak of interest. But this is cumbersome when doing peak peaking requires this option be toggled off and on continuously. 

It would be useful to make zooming EICs a little more intuitive. Maybe either turn off the Y-axis lock so you're actually zooming to the selected region or allow an option to auto zoom y-axis by the largest EIC _visible_ (rather than an off-screen peak).

**Comment by PMSeitzer** [comment]
Just remove the Y-axis lock, zooming should not consider peak groups.

**Comment by PMSeitzer** [comment]
Implemented as of 39990a1ee11465164b676d8512a81380a22a35e4
