### ISSUE TITLE
RumDB reported an ID, which didn't get suggested in Maven

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#106]
After running MzKit to generate a rumDB, I matched peaks with Maven, however, ID labeled on RumDB didn't show up as the suggested compound in compound search of Maven. I increased the precursor ppm to 20, yet, the ID labeled by MzKit still didn't make the list.

**Comment by PMSeitzer** [comment]
This is a problem in `mass_spec`, will be fixed in `mzkitchen 10`
Please hold off on running this dataset until the bug is fixed.

**Comment by PMSeitzer** [comment]
Using `mzkitchen 10` with correct adducts, should be no problem.
