### ISSUE TITLE
Maven crashed multiple times

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#109]
I had 3 sample files opened on Maven and everything I tried to bookmark my last few compounds, Maven crashed.

**Comment by ngoccalico** [comment]
https://drive.google.com/open?id=1k54QW7bnoo63aeckGrdvRj4uYB-Au9xV

this is the link to the files.

**Comment by ngoccalico** [comment]
I tried again and seemed like Maven also crashed when I tried to click on compounds in bookmark list.

**Comment by PMSeitzer** [comment]
Instructions:

1. load samples

2. adducts
[M-H]- , [M-2H]2-, [M-3H]3-

3. library of GG-KNOWNS-M009A

4. bookmarks, mass calc GUI crashes b/c of rumsdb call.

**Comment by PMSeitzer** [comment]
Completed as of f750692a49df604f2a2dd4174c7381d5891d5173
