### ISSUE TITLE
rumDB library didn't load by itself

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#111]
when opened newest ver of Maven, a screen showed the choice of the library for rumDB. however, there wasn't any choice or selection for it.

**Comment by PMSeitzer** [comment]
Hey @ngoccalico,

You'll have to import the library first before opening the file.

Once the library is loaded, when you open the `mzrollDB` file, the loaded library will appear in the drop-down menu in the dialog.

**Comment by PMSeitzer** [comment]
I added a message in the dialog with a label explaining this in 1726826a5cb8e526ce84f4ce6280ade7a8d11d30

**Comment by ngoccalico** [comment]
How do you add the rumbDB library?
