### ISSUE TITLE
Bookmarks from rumsDB library didn't show the compound names but the m/z

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#115]
While using the newest ver of Maven, I used rumbDB library to check the IDs for project X0135. However, if I tried to bookmark the compound based on the assigned MS2, the bookmark only showed the m/z as the compound name.

**Comment by PMSeitzer** [comment]
Check that this is not working when the compound is successfully associated (as through `rumsDB` association).

**Comment by PMSeitzer** [comment]
When the library is correctly associated, the `bookmarks` table will display all of the correct information.  The file was opened in `8.1.17` and saved, then re-opened in `8.1.17.1`, so the `PeakGroup groupId` information was lost.
