### ISSUE TITLE
ID from rumsDB didn't  have any suggested compound from "Compound Search" on Maven

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#116]
Project X0135- M005A-my suggested IDs from rumsDB didn't have any suggested/matched ID in "Compound Search" from Maven.

**Comment by PMSeitzer** [comment]
Need to check options + loaded libraries

**Comment by PMSeitzer** [comment]
The file was opened and saved in`8.1.17` prior to being opened in `8.1.17.1`, so the  `PeakGroup groupIds` were misnumbered.
