### ISSUE TITLE
MS2 spectrum from RumsDB library didn't show up or change

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#117]
project X0135-M005, for a certain compounds listed in rumsDB (ex: LysoCPI(d19:1) [M+K] id = 763160, m/z = 594.2759, rt =11.00 min), rumsDB library showed a list of matched compounds, however, when I clicked on it, the in-silico MS2 didn't change or show up/ respond to the highlighted compound. 
<img width="1677" alt="Screen Shot 2019-12-30 at 10 33 28 PM" src="https://user-images.githubusercontent.com/56043766/71612316-734e9b00-2b54-11ea-91ff-44d9a4db7308.png">

**Comment by PMSeitzer** [comment]
Check that correct library is associated from loading process

**Comment by PMSeitzer** [comment]
The file was saved in `8.1.17` and reopened in `8.1.17.1`, so the data in the file could no longer be properly associated to a `rumsDB` library.
