### ISSUE TITLE
Maven crashes after deleting lines in bookmarks tab

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#12]
Bookmarks seem to have an issue when deleting lines:

Shift-clicking mutliple lines and deleting them results in not all lines being deleted. Some remain highlighted.

After deleting single lines, sometimes Maven crashes without having saved (continuous saving seems to be off).

**Comment by lparsons** [comment]
I've been able to reproduce the issue where attempting to delete multiple lines and only some are deleted. I have not yet, however, been able to reproduce the crash. @Calicotobi Do you have any files or steps that reliably produce a crash? That would help in debugging.

**Comment by Calicotobi** [comment]
I have a set of .xml-files that produced a crash, hope this google-drive share links work:

https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-QkhLZmxVaDVlY2s/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-QlZtSXpzQ2NadkU/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-ZDhiSEdzUlpPcXM/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-OWh6bEhLSkM1a0E/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-ME1uOTktMHVTS3c/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-aE1pV0w0b1hzVVk/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-T201eTlHNnB5ZUU/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-VWJVQUlRX2RaNWc/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-Zmc3ZVJZQmp0b2M/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-NzgzTWxVb0N4b1k/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-VFRMWV9UblhreE0/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-RWtpYldMN2NrZHM/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-VHJzNExtalBfcVU/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-YURGYlJ5VmtJV0U/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-bEU2UDRnTXJQdW8/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-cGRXcEF3bnJOTHM/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-cnd0aXBUaDJsdTg/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-UnNOU0tBT0E2clE/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-ZUhVQ0d6a0xlU0k/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-OFBtSzFweG5PZ00/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-cDVlR1p4NE82czQ/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-UDlPU3dodTRRYm8/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-clpkdXhhR1ZPT0U/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-d0tlTXBfX3ZHZEU/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-SEl3NHE3MHkzNmM/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-WDNCaGV6SXlFWkU/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-R2tWYkJhSXZyWlk/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-aGlkYnFXSUxEU0U/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-M1NTaTRHcVFHTDQ/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-NmdLNEQ4cWpqSDA/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-UVY2WnNYSHZPeWc/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-WVhWakJXQ01pRFk/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-WnVaNm5DdFFiMGs/view?usp=sharing
https://drive.google.com/a/calicolabs.com/file/d/0BzIm4H9Q40h-cFFCTGJvRHlJMkE/view?usp=sharing

**Comment by eugenemel** [comment]
I reworked logic in deletegroup function, I am not sure what what causing this exactly, but it should be fixed now.
