### ISSUE TITLE
Maven Isotope Reporting Incorrect for some Analytes

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#130]
Maven reporting zero values for C12 parent isomer of L-Valine. Spectra view looks OK, though. Manual integration did not fix problem. 

Raw data to reproduce bug in Metabolomics Core -> GitHub Issues

**Comment by PMSeitzer** [comment]
This is likely linked to how the correlation is being computed in `mzSample->correlation()`.

Everything might be techinically correct, potentially slightly confusing UI.

Note related issue #102 (also has to do with correlation computation)

**Comment by cmsand** [comment]
I can resolve the issue for Valine by decreasing the isotope-parent correlation to -0.1, but that seems to introduce lots of noise into other amino acids. It's an OK work-around for now, but would be good to fix the issue directly.

**Comment by PMSeitzer** [comment]
New approach implemented as of 5a011b4e3fc8289036d74b85fcc4ea6d65b56f6f

**Comment by PMSeitzer** [comment]
Consider the molarity of the adduct when considering formulas - eg `[2M+H]+` should enumerate `2*molecular_formula` worth of atoms

**Comment by PMSeitzer** [comment]
Implemented molarity of adduct consideration in `maven_core`
```
e1f3b27c82f29754ee8c8ef2e637615aa318b25d
```

**Comment by PMSeitzer** [comment]
Implemented with bug fixes as of `d1e4d095d307e423008ba4a541bda11d7d4753a5`
