### ISSUE TITLE
EIC legend widget not showing scroll bar

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#135]
I have 90 samples and the space only allowed to view 10 of them. I couldn't scroll up and down to view the whole list.

![image](https://user-images.githubusercontent.com/56043766/72584754-2a128100-38a0-11ea-82c2-4cfdf30c101e.png)

**Comment by PMSeitzer** [comment]
Tried to fix this in #129, should put in some considerable effort to understand fundamentally why this isn't working.

**Comment by PMSeitzer** [comment]
This is annoying, but easy to work around (for the time being).

**Comment by PMSeitzer** [comment]
This is incredibly annoying, moving to "blocker" status to ensure this gets done in the next release cycle.

**Comment by PMSeitzer** [comment]
Hopefully this is fixed in 5991f98de3260ece4bd4ee707625b3c473c44a6e. Will re-open if it still doesn't work.
