### ISSUE TITLE
Maven cannot open mzrollDB file from the past (generated 6 months ago)

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#137]
Project X0117 in server z03, I couldn't open the mzrollDB file. I am resubmitting the dataset through mzkitchen to open and check some files. However, ideally, we should be able to open these files so we can go back and check the data from time to time.

**Comment by ngoccalico** [comment]
I submitted these mzML files to mzkitchen2 to generate the new mzrollDB, however, after importing the files, Maven stopped responding. I still cannot open those files. Attached are the codes copied from the terminal.
[Maven-issue -137.pdf](https://github.com/eugenemel/maven/files/4109799/Maven-issue.-137.pdf)

**Comment by PMSeitzer** [comment]
This turned out to be a network access issue - copying the `mzrollDB` file locally and opening the local copy fixed the problem.
