### ISSUE TITLE
UI updates to spectra notes

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#171]
- add m/z values
- expand note according to available space (left, right, up, down)
will involve adjusting `Note.cpp` class

**Comment by PMSeitzer** [comment]
This does not appear to be working for dark mode

**Comment by PMSeitzer** [comment]
dark mode is fixed as of 3d4ccd459fc8d3068460ffbfc5691a6d939e2833

**Comment by Calicotobi** [comment]
How about making the matching ion peak selectable through the popup label which opens upon hovering over the library peak top? It is sometimes very hard to select ions in the fragmentation spectra window otherwise.

**Comment by PMSeitzer** [comment]
label expansion orientation implemented as of 6309a919a81ae268fa9ef9b24397e401761ab32d

**Comment by PMSeitzer** [comment]
fragment spectra selection by clicking implemented as of a4f19d2a0414fc4d6163cf581a95736293ad6c54
