### ISSUE TITLE
Group peaks recalculation

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#177]
Group peaks do not get updated if you uncheck and recheck the option via right-click. Lags out other windows if occurring on busy EICs.

**Comment by PMSeitzer** [comment]
zooming in when "peak groups" is not checked does not redraw the circles indicating picked peaks.
checking/un-checking the "group peaks" does not trigger a redrawing of the eicwidget.

**Comment by PMSeitzer** [comment]
Completed as of 38b74b7ea7ba4efe1379e5e8da8f36526f1b0413

This is much better, but still not perfect. grouping can be enabled/disabled by toggling peak groups check box.

The peaks in a peak group can be viewed when the check box is not checked, however, if the peak group boundaries are outside of the window, the picked peak will no longer be displayed.  This allows for some modifications to the eic widget (for example, expanding the ppm range), but not others (switching to an entirely new region).
