### ISSUE TITLE
Maven unable to zoom out fully to look at full EIC peak.

### ISSUE THREAD

**Issue by angelayxu** [eugenemel/maven#186]
Using MAVEN 8.1.25 but also experienced this issue in the previous version of maven. Can't fully zoom out in EIC window. 

Able to zoom out and see peak when only a single file is selected.

Example data files are in github folder.

**Comment by PMSeitzer** [comment]
L-Valine / Betaine do not work, with "group peaks" unchecked, works as expected.

Need to have these settings to reproduce the bug:
<img width="1019" alt="Issue186-bug-settings" src="https://user-images.githubusercontent.com/1757701/76552013-e0ce5000-6450-11ea-86fa-c72aa80001c9.png">

**Comment by PMSeitzer** [comment]
Completed as of 155e13b7371c29c8be578172d40d8f65631db310
