### ISSUE TITLE
Plot isotope fraction for each sample

### ISSUE THREAD

**Issue by lparsons** [eugenemel/maven#19]
Plots of isotope fractions used to be plotted in older version of Maven, but are not in current versions (8.0+)

![old maven](https://user-images.githubusercontent.com/645128/32114184-c00c9f0c-bb10-11e7-875b-8d87371c5956.JPG)

![8 01](https://user-images.githubusercontent.com/645128/32114200-d0fa7050-bb10-11e7-8788-39dbfe98dd23.JPG)

This was requested by Zhaoyue Zhang.

**Comment by eugenemel** [comment]
The isotope plot is off by default in 8.0.x.,  You can turn it by right clicking on EIC Widget,
Like so 

![image](https://user-images.githubusercontent.com/189182/32131475-b0692608-bb63-11e7-8c9e-d3e5c8901fd1.png)
