### ISSUE TITLE
Options not showing

### ISSUE THREAD

**Issue by jopark** [eugenemel/maven#194]
After clicking 'Peak Grouping Options' from the right click menu on the main peak view panel, options show only blank page. From this point on, clicking 'Options' from the toolbar even started showing blank options page.

**Comment by PMSeitzer** [comment]
Hi @jopark,
Thanks for mentioning this.

Actually, we had seen this before: #60 

This is likely a bug in Qt, which may have been fixed for the mac os x builds but not the windows builds.  Are you using windows?

**Comment by jopark** [comment]
Yes. I’m using windows. I just downloaded the most recent build.

Thanks,
Jun

**Comment by PMSeitzer** [comment]
Hey @jopark,
I didn't see your comment until now. I'll be releasing a new version of Maven soon (`8.1.26`).  I'll see if there's anything I can do to fix the problem in the latest windows build.

**Comment by PMSeitzer** [comment]
I have updated the `appveyor.yml` file, which may or may not fix the problem, but this is worth testing in the newest release:
273fc65f1400de474362238dc988ebf2121ce8f3

**Comment by jopark** [comment]
Thank you, Phillip. I’ll try that out.
