### ISSUE TITLE
Import of multiple .msp-files into Library Manager

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#20]
Currently, it is not possible to import multiple .msp-files into the Maven Library Manager in one go. 
Although it accepts multiple selected files when browsing and selecting them via shift/command-click, only the top selected file gets imported in the end.
We currently fragment our large libraries into smaller libraries for updates and maintenance, especially the lipid libraries grow immensely in size and variety. So we end up currently with a pool of over 30 sub-libraries (per ion-mode) of which we import specific libraries dependent on the project at hand.
Can a multiple-file import be added to the Library Manager without problems? This would help immensely with setting up Maven libraries.

Cheers,

Tobi

**Comment by PMSeitzer** [comment]
I think it would be easier to group the `msp` files prior to loading, something like `cat msp_file1.msp msp_file2.msp > msp_1_and_2.msp`.  Currently, there are lipid libraries that contain all of the lipid classes.
