### ISSUE TITLE
some lipid classes didn't show the annotation of fragments on the MS2 windows

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#207]
![image](https://user-images.githubusercontent.com/56043766/81225589-514fa400-8f9e-11ea-811f-6e0b3d1282f5.png)

The MS2 of the library didn't show the annotation of the fragment while the library clearly has them

![image](https://user-images.githubusercontent.com/56043766/81225668-7217f980-8f9e-11ea-9f2d-922628c548d6.png)

**Comment by PMSeitzer** [comment]
Hey @ngoccalico, Are you sure that the library file corresponds to the compound that is displayed in the screen?

**Comment by ngoccalico** [comment]
Hi @PMSeitzer , I am pretty sure it is the same library.
This is another example

![image](https://user-images.githubusercontent.com/56043766/81322553-050d6e00-9049-11ea-83d9-2e3fb9a8d0e4.png)

**Comment by PMSeitzer** [comment]
This problem was fixed by deleting the `20191022-Calico-Lipids-neg` library from the library dialog, and re-importing using MAVEN version `8.1.25`.  The library had been loaded into `ligand.db` using an older version that did not save the fragment annotations.
