### ISSUE TITLE
MAVEN crashes on subset DB

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#22]
From Bryson:
```
Hi Eugene,  

I'm having Maven crash on a data set I'm tring to work up.  Below is the output when the crash happens.  Every time it seems to be when I am switching between compounds in the list of standards (though not on any specific one).  

Any help?

-------

overlayCompound() L-Arginine #theory=51     #obs=230           #matched=0
SpectraWidget::setScan(scan,min,max) : 0
MassCalcWidget::setPeakGroup(PeakGroup* grp)
SpectraWidget::setScan(scan)
overlayCompound() L-Arginine #theory=51     #obs=230           #matched=0
SpectraWidget::setScan(scan,min,max) : 0
SpectraWidget::setScan(peak)
Isotope Calculation:  true false false true
SpectraWidget::setScan(scan)
Scans=16
Reference
26165.134777.127610.995029.297850.411754212001366417.816212728435012160315925213585418092112947198223.1
GalleryWidget::replot()
GalleryWidget::resize()
GalleryWidget::replot()
MainWindow::bookmarkPeakGroup(group)
 EicWidget::setFocusLine(float rt)
LigandWidget::showLigand()
getUserAdduct::[M-H]-
setCompoundFocus:Ornithine [M-H]- 1.24 mass=132.09 mz=131.083
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00186174 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00187181 0.890546 2.08145
 EicWidget::computeEICs()
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00188187 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00189193 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00190199 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00191206 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00179127 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00180134 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.0018114 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00182146 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00183153 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00184159 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00185165 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00186171 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00187178 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00188184 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.0018919 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00190196 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00191203 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00192209 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00180131 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00181137 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00182143 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.0018315 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00184156 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00185162 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00186168 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00187175 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00188181 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00189187 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00190194 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.001912 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00192206 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00193212 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00173104 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00174108 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00175111 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00176114 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00177118 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00178121 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00179125 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00174111 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00175117 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00176123 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.0017713 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00178136 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00179142 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00180148 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00181155 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00182161 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00183167 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00184173 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.0018518 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00186186 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00187192 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00175114 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.0017612 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00177127 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00178133 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00179139 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00180145 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00181152 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00182158 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00183164 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00184171 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00185177 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00186183 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00187189 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00188196 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00176117 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00177124 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.0017813 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00179136 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00180142 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00181149 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00182155 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00183161 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00184168 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00185174 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.0018618 0.890546 2.08145
           computeEICs() pullEics().. msec= 34
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00187186 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00188193 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00189199 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00177121 0.890546 2.08145
Start groupCount= 18
Stop groupCount= 18
           groupPeaks() msec= 36
           computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x0
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00178127 0.890546 2.08145
getEIC(mzrange,rtrange,mslevel): is empty: 50.0016 0.00179133 0.890546 2.08145
Maven(92858,0x70000ca8a000) malloc: *** mach_vm_map(size=14757395258967642112) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

**Comment by brysonbennett** [comment]
DB and files associated with the crash are shared in Google Drive:  

DiversityOutcross/2019_03_29_reduced_datasets/metabolites_neg_files

mzrollDB: DiversityOutcross/2019_03_29_reduced_datasets/metabolites_neg (1).mzrollDB

associated files are in: DiversityOutcross/2019_03_29_reduced_datasets/metabolites_neg_files

I created the error by loading one of the msp files associated with M001A, and working through the list.  I would bookmark a peak if it looked good, then select a new compound from the list.  IT was typically during the step of selecting a new compound I would get the crash.  Happy to sit with you and try to reproduce it if that is helpful.

**Comment by PMSeitzer** [comment]
Bryson, can you point me towards an msp file associated with M001A that you tried?

**Comment by brysonbennett** [comment]
mzrollDB: DiversityOutcross/2019_03_29_reduced_datasets/metabolites_neg
(1).mzrollDB

associated files are in:

DiversityOutcross/2019_03_29_reduced_datasets/metabolites_neg_files

Thanks!

**Comment by brysonbennett** [comment]
LigandWidget::showLigand()
getUserAdduct::[M-H]-
setCompoundFocus:Dimethylglycine [M-H]- 1.52 mass=103.063 mz=102.056
 EicWidget::computeEICs()
       	computeEICs() pullEics().. msec= 57
Start groupCount= 19
Stop groupCount= 19
       	groupPeaks() msec= 62
       	computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x0
 EicWidget::setFocusLine(float rt)
addMS2Events()  found= 359
 EicWidget::setFocusLine(float rt)
Isotope Calculation:  true false false true
SpectraWidget::setScan(scan)
overlayCompound() Dimethylglycine #theory=22   	 #obs=519      	 #matched=0
SpectraWidget::setScan(scan,min,max) : 0
LigandWidget::showLigand()
getUserAdduct::[M-H]-
setCompoundFocus:Creatinine [M-H]- 1.52 mass=113.059 mz=112.052
 EicWidget::computeEICs()
       	computeEICs() pullEics().. msec= 31
Start groupCount= 29
Stop groupCount= 29
       	groupPeaks() msec= 32
       	computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x0
 EicWidget::setFocusLine(float rt)
addMS2Events()  found= 0
 EicWidget::setFocusLine(float rt)
Isotope Calculation:  true false false true
SpectraWidget::setScan(scan)
overlayCompound() Creatinine #theory=16	 #obs=0	 #matched=0
SpectraWidget::setScan(scan,min,max) : 0
LigandWidget::showLigand()
getUserAdduct::[M-H]-
setCompoundFocus:Trehalose [M-H]- 1.52 mass=342.116 mz=341.109
 EicWidget::computeEICs()
       	computeEICs() pullEics().. msec= 30
Start groupCount= 23
Stop groupCount= 23
       	groupPeaks() msec= 31
       	computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x0
 EicWidget::setFocusLine(float rt)
addMS2Events()  found= 25
 EicWidget::setFocusLine(float rt)
Isotope Calculation:  true false false true
SpectraWidget::setScan(scan)
overlayCompound() Trehalose #theory=50 	 #obs=229      	 #matched=0
SpectraWidget::setScan(scan,min,max) : 0
SpectraWidget::setScan(scan)
MassCalcWidget::setPeakGroup(PeakGroup* grp)
SpectraWidget::setScan(scan)
MassCalcWidget::setPeakGroup(PeakGroup* grp)
SpectraWidget::setScan(scan)
overlayCompound() Trehalose #theory=50 	 #obs=229      	 #matched=0
SpectraWidget::setScan(scan,min,max) : 0
SpectraWidget::setScan(peak)
Isotope Calculation:  true false false true
SpectraWidget::setScan(scan)
Scans=15
Reference
042709.924518339540352447255423052130158627939733139493331231921655821219213096562670.7
[M+AcO]- -1 281.087
[M-H2O-H]- -1 360.125
GalleryWidget::replot()
MainWindow::bookmarkPeakGroup(group)
 EicWidget::setFocusLine(float rt)
LigandWidget::showLigand()
getUserAdduct::[M-H]-
setCompoundFocus:4-Guanidinobutanoic acid [M-H]- 1.52468 mass=145.085 mz=144.078
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00362206 1.1311 2.40472
 EicWidget::computeEICs()
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00363212 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00364218 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00365225 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00366231 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00367237 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00368243 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.0036925 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00370256 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00371262 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00372268 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00373275 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00374281 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0008 0.00375287 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00341109 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00342112 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00343116 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00344119 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00345122 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00346126 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00347129 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00348132 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00349136 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00350139 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00351142 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00352146 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00353149 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00342115 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00343121 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00344128 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00345134 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.0034614 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00347147 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00348153 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00349159 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00350165 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00351172 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00352178 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00353184 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00354191 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00355197 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00356203 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00357209 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00358216 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00359222 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00360228 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00361235 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00362241 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00363247 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00343119 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00344125 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00345131 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00346137 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00347144 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.0034815 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00349156 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00350163 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00351169 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00352175 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00353181 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00354188 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00355194 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.003562 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00357206 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00358213 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00359219 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00360225 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00361232 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00362238 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00363244 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.0036425 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00344122 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty:     	computeEICs() pullEics().. msec= 39
50.0021 0.00345128 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00346134 1.1311 2.40472
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00347141 1.1311 2.40472
Start groupCount= 14
Stop groupCount= 14
       	groupPeaks() msec= 40
       	computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x0
getEIC(mzrange,rtrange,mslevel): is empty: 50.0021 0.00348147 1.1311 2.40472
 EicWidget::setFocusLine(float rt)
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6

**Comment by PMSeitzer** [comment]
The problem appears to be the mzrollDB file (corrupt SQLite file). Remaking the file fixes things in MAVEN.
