### ISSUE TITLE
Feature: Separate rows for RT and MS2 event arrows in EIC window

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#228]
Currently, MS2 events are shown as little triangles over the RT bar in the EIC window. While this is not such a big issue for most metabolites, some other compounds, especially lipids or multipeak compounds can have a lot of events, completely clogging up any readable retention times. Would it be possible to put the triangles and the RT-bar upon each other rather than over each other for more clarity? 

![Screen Shot 2020-06-18 at 7 51 26 PM](https://user-images.githubusercontent.com/31489371/85091806-2d869d00-b19d-11ea-8f49-7459d26fb18d.png)

**Comment by PMSeitzer** [comment]
Hey @Calicotobi,
I think we can do that.  Just so you know, you can also view individual RT events by navigating to `Widgets -> MS2 Scans List`.  You can toggle the appearance of MS2 events by right-clicking on the EIC widget and selecting `Show MS2 Events`.
![show_hide_Ms2-events](https://user-images.githubusercontent.com/1757701/85097964-06849700-b1ae-11ea-9216-d9982b1a7c63.png)

See screenshots.
![Screenshot-Ms2-events](https://user-images.githubusercontent.com/1757701/85097961-02f11000-b1ae-11ea-8273-d0734298a7f0.png)

**Comment by PMSeitzer** [comment]
After discusison, toggling using the right-click menu is an acceptable solution.
