### ISSUE TITLE
CSV export not working

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#236]
See dataset for #235 

Try to export all groups

.csv button stays grayed out,

dialog does not appear immediately

stochastic behavior

**Comment by PMSeitzer** [comment]
Only Tobi has observed this, and it does not happen reproducibly.

**Comment by Calicotobi** [comment]
I have an update on this: 
Also the corresponding windows for editing peak groups or setting up a RT alignment file from selected groups do not pop up. When I minimize the Maven window into the dock, these windows suddenly do pop up. This was reproducible every time I tried so far.

**Comment by PMSeitzer** [comment]
Need to check with @tobimaile if this is still a problem.
