### ISSUE TITLE
Analyzing X0081 neg brain samples not producing enough peak groups

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#247]
Data: `X0081_M004A`

Library: `20191022-Calico-Lipids-neg`

**Comment by PMSeitzer** [comment]
`met_datasets/test-mzXML` 21 samples

**Comment by PMSeitzer** [comment]
Consider re-wording some of the labels in the peaks dialog while working on this case.

**Comment by ngoccalico** [comment]
After analyzing the files MzXML  from Mzkitchens, the peak identification reported in rumbsDB doesn't match with the identification suggested on Maven.

**Comment by ngoccalico** [comment]
![image](https://user-images.githubusercontent.com/56043766/89055897-08468c00-d310-11ea-9393-5cc68c6698e8.png)
 I think this bug made it difficult to analyze the data. I feel like I am missing out identifications

**Comment by PMSeitzer** [comment]
Hey @ngoccalico, yes, this is a very serious bug. I am working on it now.

**Comment by ngoccalico** [comment]
This happened to the dataset in M005A of X0081. You should be able to open the mzDBroll file from server z03 from the metafile folder.

**Comment by PMSeitzer** [comment]
The low number of results was caused by this changeset:
https://github.com/eugenemel/maven/commit/9cfb90b6a87773d718c1d65dc3f39927cbf6f7ce

Previously, user-specified parameters associated with modifying smoothed EICs were not being passed through.  Per last changeset, these parameters are passed through. However, the defaults are too strict.

**Comment by PMSeitzer** [comment]
After talking to ngoc, decided on a new set of default parameters:

![defaults_1](https://user-images.githubusercontent.com/1757701/89064705-5616c080-d31f-11ea-93bd-bb8e2481360b.png)

![defaults_2](https://user-images.githubusercontent.com/1757701/89064716-59aa4780-d31f-11ea-89f1-9117cb7f5617.png)

**Comment by PMSeitzer** [comment]
It looks like there might be another bug - unable to recover 1641 IDs using above parameters repeatedly.

![peak_detection_1641](https://user-images.githubusercontent.com/1757701/89066127-bdce0b00-d321-11ea-9b3a-e63a752eedb5.png)

**Comment by PMSeitzer** [comment]
Completed as of 521583d23c46d983d41170de704f5974da9bd411.

The problem turned out to be the smoothing algorithm (Savitzky-Golay). Switching to Gaussian smoother fixes the issue.

See #249 follow-up case.  For the time being, avoid using Savitzky-Golay smoother (recommended).

**Comment by PMSeitzer** [comment]
On second thought, disabling Savitzky-Golay smoothing for peaks searches as of 14fcb238abef7b872faa2a0fcd28faa9f4710a76
