### ISSUE TITLE
Browsing in compounds list does update EIC window only on Exact Mass

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#266]
When I browsed the compounds list, it did only update the EIC window when I hit a compound with a different exact mass. Compounds of the same exact mass but with different precursor m/z (due to different adducts) where not displayed and I had to type in the precursor m/z to see them in the EIC. See video in zip-file.

[CompoundsList.zip](https://github.com/eugenemel/maven/files/5066428/CompoundsList.zip)

Is this a bug? I think the EIC should get updated from the precursor m/z rather than from exact mass.

**Comment by PMSeitzer** [comment]
I agree that this behavior is unexpected - I will make the eic widget update based on `precursorMz` changes.

**Comment by PMSeitzer** [comment]
Implemented as of 4ef325a01d31dd132cd6abbebcd3fecf23b879aa
