### ISSUE TITLE
Patch up memory leaks in bookmarking

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#27]
Memory consumption is increasing on the order of 0.5- 1GB with every bookmark, indicating serious memory leaks.
![image](https://user-images.githubusercontent.com/1757701/59464368-17e9d500-8ddd-11e9-9ff3-bcf5b6782f75.png)

**Comment by PMSeitzer** [comment]
isotopic peak picking is turned on, then the memory leak occurs, if it is not turned on, no memory leak

**Comment by PMSeitzer** [comment]
Confirmed by Eugene:
```
I think it is during bookmark -> isotope detection. When I turn off C13/N15 isotope detection and bookmark, memory stays constant. 
```

**Comment by PMSeitzer** [comment]
<img width="1047" alt="Screen Shot 2019-06-13 at 1 39 03 PM" src="https://user-images.githubusercontent.com/1757701/59465853-b1ff4c80-8de0-11e9-8299-f17011569acd.png">

**Comment by PMSeitzer** [comment]
Screenshot to turn off isotopic peaks

**Comment by eugenemel** [comment]
I found the issue, correlation subroutine in mzSample.cpp .. pulled EIC*, but never deleted the EIC structure. This was called many many times in the pullIsotopes subroutine, creating a huge memory leak.

```
    EIC* e1 = mzSample::getEIC(mz1-ppm1, mz1+ppm1, rt1, rt2, mslevel);
    EIC* e2 = mzSample::getEIC(mz2-ppm2, mz2+ppm1, rt1, rt2, mslevel);
    double correlaton = mzUtils::correlation(e1->intensity, e2->intensity);
```
