### ISSUE TITLE
Isotopic workflow UI optimizations

### ISSUE THREAD

**Issue by eugenemel** [eugenemel/maven#287]
It would be good to bring back/unhide some of the UI that was used for full scan only isotopic workflow that is still used by some users. The database search button and isotopic bars are hidden. 
[Maven update broken isotopic workflow.pdf](https://github.com/eugenemel/maven/files/5144730/Maven.update.broken.isotopic.workflow.pdf)

**Comment by PMSeitzer** [comment]
Hey @eugenemel, I'm happy to do this work, but what specifically do you think we should do?

**Comment by PMSeitzer** [comment]
Many of the recent changes associated with `8.1.27.27` address the isotopes UI.
