### ISSUE TITLE
Fragmentation scoring producing bad values

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#31]
Identified by Bryson in `Maven 8.0.18`.  See screenshot.
![frag_scores_off](https://user-images.githubusercontent.com/1757701/59700454-2999f680-91a8-11e9-941d-a03eeff724ec.png)

**Comment by PMSeitzer** [comment]
The `CompoundSearch` widget appears to be disconnected from the fragmentation scoring associated with the full database search.

Additionally, choosing the `numRefMatches` option in the `CompoundSearch` causes the program to crash.

**Comment by PMSeitzer** [comment]
It appears that this is a display problem with the `Fragmentation Spectra` plot.

The plot seems to be displaying the spectral peaks for the `[M-H]-` form of `PI(18:0,24:0)` instead of the `[M+NaOCH-H]-` form (as expected).

Somehow the proper adduct information is not being delivered to the fragmentation plot.  Probably, the fragmentation plot is falling back to hard-coded adduct constants instead of the user-specified adducts list.

I will incorporate this work in Issue #26 in reforming the fragmentation score plot.

**Comment by brysonbennett** [comment]
I'm not quite clear.  There is no adduct of type [M+NaO2CH-H]- in our database/msp files.  Matching against the [M-H]- is functioning as intended for Maven (As maven calculates the masses of the adducts to check against based on ADDUCTS.csv).  It should score that to a good score, if behaving as intended.  There are also spectra for e.g. [M+FA-H]  in the compound list, they just are not scoring as well.  Fundamentally, I think this is just a problem in correctly calculating scores between the experimental spectra and the options in the databases that are loaded.  

I'm not quite clear what mzkit is doing to score these, as it is obviously handling the M+O2CH-H adduct type (which I did not think it did).

**Comment by PMSeitzer** [comment]
The problem is more complicated, with some spectral matches scoring incorrectly.

**Comment by PMSeitzer** [comment]
To reproduce:
spectral library, use `20190517-Calico-Lipids-neg.msp`
Dataset: DOMouseReduced folder contains the mzroll object and files

**Comment by PMSeitzer** [comment]
`Find Peaks` button is completely broken - crashes right away

**Comment by PMSeitzer** [comment]
Consider restructuring PeakDetector search into a single dialog?
