### ISSUE TITLE
MAVEN Crashes after attempting to save

### ISSUE THREAD

**Issue by kukurugya** [eugenemel/maven#32]
MAVEN has been crashing after attempts to save a large dataset. It produces the following error: "QSqlError("10", "Unable to fetch row", "disk I/O error")". I have provided screenshots with more information in the attached document. 

[MAVEN Crashes after attempting to save.pdf](https://github.com/eugenemel/maven/files/3302743/MAVEN.Crashes.after.attempting.to.save.pdf)

**Comment by PMSeitzer** [comment]
Version = `8.0.17`

**Comment by PMSeitzer** [comment]
As discussed, downloading the files locally avoids the problem.
