### ISSUE TITLE
Maven crashed when using looking at labeling data

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#322]
After processing files via MzKitchen, I started doing the peak picking manually and via the isotopic wizard. However, after bookmarking the isotopic compounds, Maven kept crashing and can't be used. @PMSeitzer can check the data from metadata folder project X0167-M003A-qe2. Thanks!

**Comment by PMSeitzer** [comment]
adding `stalled`, since this bug was observed in an older version of maven (`8.1.27.6`).  Not yet observed in `8.1.27.14`.
