### ISSUE TITLE
MS2 reference spectra doesnt line up when zoomed in

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#342]
When zooming in on MS2 spectra the diagnostic green-ticked line doesn't match up with reference spectra but instead it lines up with observed spectra. Note scale on the X axis here is highly zoomed. 

<img width="809" alt="Screen Shot 2021-01-21 at 3 52 38 PM" src="https://user-images.githubusercontent.com/9013133/105746535-68e80780-5ef4-11eb-8cd2-3b57ec95c3be.png">

**Comment by PMSeitzer** [comment]
Implemented as of 221e59e4828c9e250abb068f55d679c8ad49e7a0
