### ISSUE TITLE
Compilation issue: can't find reference to isotopeFrac, percentRelative in mzLink class

### ISSUE THREAD

**Issue by eugenemel** [eugenemel/maven#343]
https://github.com/eugenemel/maven/blob/bb44f6cfd0a8bd8d716e799b28f73caa8b7f1db0/src/maven/csvreports.cpp#L287

**Comment by PMSeitzer** [comment]
Sorry! I forgot to push `maven_core`:
https://github.com/eugenemel/maven_core/commit/560dee5db09270ade28470584d0e9b27d314b4da

I rebuilt and everything compiled on my machine.
