### ISSUE TITLE
MAVEN not showing reference spectra when using add_direct_infusion_search_results

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#345]
Library compound isnt showing up for the internal standard results and no reference spectra is shown, but works fine with my the regular search results table. Will add all documents to the google drive to reproduce

<img width="628" alt="Screen Shot 2021-02-02 at 11 53 46 AM" src="https://user-images.githubusercontent.com/9013133/106654702-52bdf500-654d-11eb-9fc9-2dbfebc8f1c0.png">

**Comment by cmsand** [comment]
Supporting files here:
https://drive.google.com/drive/u/0/folders/1Julkw8gi5BUs6LmT7--mOd8bAk9qvwHs

**Comment by PMSeitzer** [comment]
This is likely the result of formatting inconsistencies for compound ids in `20200803-Calico-Lipids-all-IS.msp` and in the `mzrollDB` file.  The inconsistency was corrected in later versions of the IS file, such as `20201215-Calico-Lipids-all-IS.msp`.

**Comment by PMSeitzer** [comment]
Switching out the IS file worked.  Renamed method in d0f2d4ac7f51adecaadd80b1638a3c550abf51f1, otherwise no changes.
