### ISSUE TITLE
When using istope tracing in Maven, bookmark of the isotope recorded as unknown instead of the compoundID

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#376]
![image](https://user-images.githubusercontent.com/56043766/112377911-84c51b00-8ca3-11eb-8db3-a8c09be5266a.png)

**Comment by PMSeitzer** [comment]
This may be related to #371

**Comment by PMSeitzer** [comment]
`X0176-M003A-qe1-rerun`

Compound: `Fructose-6-Phosphate`, should show this compound instead of `Unknown_<formula>`

don't use the mutant folder - just the original `mzML` outside the folders, and associated mzkitchen

**Comment by PMSeitzer** [comment]
earlier RT is Fructose-6-phosphate, later RT is glucose-6-phosphate

**Comment by PMSeitzer** [comment]
As a part of this case, also fix the `ligandwidget` to properly respect `unloadCompoundLibrary()` events, and avoid dangling pointer bugs.

Additionally, switching compounds in the `ligandwidget` needs to set `_alwaysDisplayGroup` to nullptr

**Comment by PMSeitzer** [comment]
It appears that switching the `ligandwidget` compound does always set `_alwaysDisplayGroup` in the eic widget to `nullptr`, however, there are some updating bugs associated with the isotopes widget.

Additionally, the isotopes widget should also update the `Adduct*`, not just the `Compound*`.  This is a big deal for getting the correct m/z, and could cause confusion when the eicwidget has one adduct and the isotopewidget has another.

**Comment by PMSeitzer** [comment]
Completed as of 33ec19753968ad0241eecb5e308455a4da3b2bdc.  Note number of smaller issues tied to this case.
