### ISSUE TITLE
Maven crashes when children peaks unselected

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#406]
Issue happened when selecting bookmarks for isotope analysis

**Comment by cmsand** [comment]
Log and screen recording https://drive.google.com/drive/u/0/folders/14_-sXbnoEBPrFnhzYS0kHupc3m-Zuuvw

**Comment by PMSeitzer** [comment]
This appears to be completed as of 6fec94545298ccd4e375e0b1b72835af7683ce9a.  After 1b17140d86eef2776841346f27f75f36c2776a95, could not reproduce the crash.
