### ISSUE TITLE
EIC X Axis - Display Retention Time Under MS2 Events

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#415]
In reviewing metabolomics data, the X axis RT labels are often covered by MS2 events. Would be helpful to move axis labels for visibility. 

Using Maven 8.1.27.28

Example screenshot:
![Screen Shot 2021-05-01 at 3 18 15 PM](https://user-images.githubusercontent.com/9013133/116796348-92cf3e00-aa90-11eb-9a47-082c88337b52.png)

**Comment by PMSeitzer** [comment]
Hey @cmsand, you can right click on the EIC Widget and uncheck `Select MS2 Events`.

![Screen Shot 2021-05-02 at 12 59 16 PM](https://user-images.githubusercontent.com/1757701/116825920-49d9c100-ab46-11eb-9d6e-b4d02f9ad571.png)

Does that fix your problem?

I could make this a button if the right-click menu is too cumbersome.  Moving the axis would involve more work, but is possible.

**Comment by cmsand** [comment]
I select the MS2 events a lot for confirmation of a peak. Especially when the EIC has multiple peaks it would nice to be able to see the RTs and select MS2 events from each peak. A button to quickly toggle MS2 events on/off could be a workaround though.
