### ISSUE TITLE
Compound Search does not update EIC widget for alternate IDs

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#434]
Maven 8.1.27.32
Data: X0177-M004B

I ran a search within maven for lipids. When annotating peaks, the compound search widget is not updating the EIC pane with the selected compound name, instead the original compound ID'ed form the search is shown. MS2 is updating correctly. But when I bookmark the original ID persists. 

Screenshot of an alternate ID selected in the compound search pane, but the EIC pane still shows the original ID. 
![Screen Shot 2021-06-14 at 11 35 47 AM](https://user-images.githubusercontent.com/9013133/121941886-ad8a0900-cd04-11eb-8a6f-e0ed2e0124cf.png)

**Comment by cmsand** [comment]
After working with this new feature I think it's only cumbersome for bookmarked IDs. If youre working within the search table exclusively then having the right-click option to overwrite IDs with a Compound Search ID is nice and easy. When everything is a a bookmark then matching an ID across 3 tables at once (Detected Features, Compound Search, and bookmarks) is a little clumsy. 

Unfortunately the feature to overwrite ID with a Compound Search ID isn't enabled in Detected Features. See Issue #435 for this request

**Comment by PMSeitzer** [comment]
This was an intentional decision implemented in #426 , however, easy to revert if desired.

**Comment by PMSeitzer** [comment]
Completed as of f590f528fbabe5b97acebed092cb35ad1892ac85
