### ISSUE TITLE
Add ability to overwrite ID with Compound Search ID in Detected Features table

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#435]
Add right click option to "Set Compound Search Selected Compound" in MAVEN-searched table (Detected Features).

**Comment by PMSeitzer** [comment]
This was recently implemented for `clamdB` and `Bookmarks` table in #429 .  This ticket asks to make this option available for all peaks tables.

**Comment by PMSeitzer** [comment]
Completed as of 8891b46a4541ad09b492af667b3271f05d19ac5f
