### ISSUE TITLE
Name in the bookmarks doesn't match Compound Search table

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#440]
Previously, when I review an entry from clamDB table, the compoundsearch shows other matches from other databases in real-time. If I want to bookmark the entry with a new name from the compound Search, all I needed to do was click on the name of the compound column from compound Search and bookmark it, then the name is updated with my assignment. 

With the most recent update, regardless of what I assigned from Compound Search, the name of compounds from bookmark is always the same as clamDB. The video should show an example. The compound that got bookmarked should be Methylsuccinic acid, not Glutaric acid.

**Comment by ngoccalico** [comment]
Link to the video
https://drive.google.com/open?id=1rfU257qLcGPxMLzmneZTZ3kwEyXku-5r&authuser=ngoc%40calicolabs.com&usp=drive_fs

**Comment by PMSeitzer** [comment]
Based on the video, it looks like this is another instance of #434 
This was an intentional design decision from #426, but I think we will revert the behavior.
