### ISSUE TITLE
Isotopic peaks are not being extracted correctly

### ISSUE THREAD

**Issue by brysonbennett** [eugenemel/maven#46]
Isotopic peaks picked by Maven seem to be incorrect, both in the isotope barplot and in the extracted data when exported to .tab file.  Older versions (we tested 8.0.12) seem to be working correctly, so this may be a bug introduced when the memory leak related to isotope picking was fixed.

**Comment by cmsand** [comment]
Example isotope data exported from Maven 8.1.4 and 8.0.12
Data from X0123-M002A Arginine

Isotope Detection Settings:
Samples are Labeled: D2 Labeled, C13 Labeled
Minimum isotope-parent correlation: 0.30
Isotope is within [X] scans of parent: 5 scans
Maximum % Error to natural abundance: 100.00%
Correct for natural C13 isotope abundance: FALSE

[arg_MavenExport8.1.4.xlsx](https://github.com/eugenemel/maven/files/3692319/arg_MavenExport8.1.4.xlsx)
[arg_MavenExport8.0.12.xlsx](https://github.com/eugenemel/maven/files/3692320/arg_MavenExport8.0.12.xlsx)

**Comment by eugenemel** [comment]
I think I fixed it, the was a logic bug in isotope extraction subroutine. a384d8e

**Comment by PMSeitzer** [comment]
Will close after this has been tested.

**Comment by cmsand** [comment]
Maven 8.1.11 is mostly functional for isotope reporting, but found an example where the exported values (and corresponding isotope widget in GUI) give 100% C12 parent (no isotopes are found), but manual inspection of  the MS1 spectra shows C13 and D labels are present. 

Experiment: X0131-M001A
Sample: X0131-M001A-34_S30

Screenshot of Isotope widget showing 100% C12 parent (red bar), and corresponding MS1 spectra highlighting C13 peak. Deuterium peak is also present. 

![Screen Shot 2019-10-21 at 2 13 45 PM](https://user-images.githubusercontent.com/9013133/67244074-c9dd8180-f40d-11e9-8373-c0b4217829d8.png)

Strangely, the bookmarked/exported data also have different values for the C12 parent. Manually extracting EIC agrees with 2.47E+08 value. 

note | compound | X0131-M001A-34_S30.mzML
-- | -- | --
  | L-Glutamine | 2.47E+08
C12 PARENT | L-Glutamine | 1.97E+08

**Comment by PMSeitzer** [comment]
Closing this issue, will fix followup issue in as #72.
