### ISSUE TITLE
Misallocation of amino acid peaks

### ISSUE THREAD

**Issue by bk-calico** [eugenemel/maven#471]
X0188/M003A Several amino acid peaks (e.g. asparagine, aspartic acid, methionine) in clamdb table are being misidentified with nearby noise
<img width="1790" alt="Screen Shot 2021-07-30 at 1 52 35 PM" src="https://user-images.githubusercontent.com/87673832/127710476-1027e863-4e5f-4119-9906-e9d8e741985e.png">
<img width="1792" alt="Screen Shot 2021-07-30 at 1 53 23 PM" src="https://user-images.githubusercontent.com/87673832/127710569-06cc20d9-539b-4924-9815-7ef6dfa0fdf3.png">

**Comment by ngoccalico** [comment]
@PMSeitzer this data was the output from mzkitchen.

**Comment by PMSeitzer** [comment]
Hey @ngoccalico  and @bk-calico , Can we schedule some time to look at this data all together, so I can get a better sense of the problem?

**Comment by bk-calico** [comment]
Yes, let's discuss soon!

Here's the folder with the mzroll.db file

https://drive.google.com/drive/folders/1-p8JuIb659pXYr_YGUMD6FbbIS42HSso?usp=sharing

**Comment by PMSeitzer** [comment]
This did not turn out to be an issue, just a consequence of a low `rtStepSize` parameter (see https://github.com/calico/mass_spec/issues/685)
