### ISSUE TITLE
Peak grouping missing obvious peak

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#482]

**Comment by PMSeitzer** [comment]
The issue folder is here:
https://drive.google.com/drive/folders/1bBZOBfM3MPjTmLlsAhSv133e9FGSkvtK

**Comment by PMSeitzer** [comment]
This may be related to #478

**Comment by ngoccalico** [comment]
data has been uploaded @PMSeitzer

**Comment by PMSeitzer** [comment]
To show the peak groups where this phenomenon occurs,
```
select peaks.groupId, AVG(peakMz), AVG(rt) 
from peakgroups inner join peaks on peakgroups.groupId = peaks.groupId 
group by peaks.groupId 
having peakgroups.label LIKE '%r%'
```
In the `mzrollDB` file from the mzkitchen run.

**Comment by PMSeitzer** [comment]
Here is an example that was provided:

![bad_peak_pick_example_choose_single_max](https://user-images.githubusercontent.com/1757701/130367594-5b8860f1-8dc6-4db1-9804-60105feb9df7.png)''

Here is what is happening:
Peak picking applied to the merged EIC finds 3 peak maxima, at `4.91292`, `4.9845`, and `5.05608`:

```
...
i=283 rt=4.90099 3.73915e+07 (spline=3.19703e+07) NONE

** i=284 rt=4.91292 3.20907e+07 (spline=3.24702e+07) MAX ** 10

i=285 rt=4.92485 3.38973e+07 (spline=3.18426e+07) NONE
i=286 rt=4.93678 2.93563e+07 (spline=3.06989e+07) NONE
i=287 rt=4.94871 3.079e+07 (spline=2.98309e+07) NONE
i=288 rt=4.96064 2.10754e+07 (spline=2.98112e+07) NONE
i=289 rt=4.97257 3.62405e+07 (spline=3.04884e+07) NONE

** i=290 rt=4.9845 3.15504e+07 (spline=3.09492e+07) MAX ** 11

i=291 rt=4.99643 3.28631e+07 (spline=3.02472e+07) NONE
i=292 rt=5.00836 3.41381e+07 (spline=2.82432e+07) NONE
i=293 rt=5.02029 1.95337e+07 (spline=2.58757e+07) NONE
i=294 rt=5.03222 1.92726e+07 (spline=2.44507e+07) NONE
i=295 rt=5.04415 2.40639e+07 (spline=2.43404e+07) NONE

** i=296 rt=5.05608 2.8173e+07 (spline=2.45861e+07) MAX ** 12

i=297 rt=5.06801 2.8254e+07 (spline=2.39794e+07) NONE
...
```

The peak grouping algorithm is blind to intensity, it only tries to associate peaks to groups based on RT proximity.  The result of this peak grouping leads to these associations:
```
Peak Group 10:
	X0188-M002A-01_TrueBlank.mzML, rt=4.92664, I=78957.3
	X0188-M002A-02_std002C.mzML, rt=4.91876, I=8.94094e+06
	X0188-M002A-03_std007C.mzML, rt=4.94247, I=5.71946e+07
	X0188-M002A-04_2002.mzML, rt=4.93664, I=5.4565e+07
	X0188-M002A-05_1001.mzML, rt=4.47002, I=21642.4
	X0188-M002A-06_1501.mzML, rt=4.9454, I=1.98795e+07
	X0188-M002A-07_2502.mzML, rt=4.94541, I=4.00363e+07
	X0188-M002A-08_2501.mzML, rt=4.90682, I=6.97796e+07
	X0188-M002A-09_1502.mzML, rt=4.9319, I=1.08335e+08
	X0188-M002A-10_2001.mzML, rt=4.91909, I=9.84535e+07
	X0188-M002A-11_1002.mzML, rt=4.85669, I=2.34593e+06
	X0188-M002A-12_std007C.mzML, rt=4.9383, I=5.89538e+07
	X0188-M002A-13_std002C.mzML, rt=4.91136, I=8.81352e+06
	X0188-M002A-14_TrueBlank.mzML, rt=4.93811, I=106223

Peak Group 11:
	X0188-M002A-01_TrueBlank.mzML, rt=4.55295, I=3969.97
	X0188-M002A-02_std002C.mzML, rt=4.49966, I=4742.3
	X0188-M002A-05_1001.mzML, rt=4.95317, I=2.02556e+07
	X0188-M002A-11_1002.mzML, rt=4.95421, I=2.51551e+06
	X0188-M002A-13_std002C.mzML, rt=4.49757, I=10964.3
	X0188-M002A-14_TrueBlank.mzML, rt=4.61807, I=7345.6

Peak Group 12:
	X0188-M002A-01_TrueBlank.mzML, rt=5.39027, I=9992.96
```

**Comment by PMSeitzer** [comment]
During peakdetector's `reduceGroups()`, a `deleteFlag` is set on one or both groups.  When two groups overlap in RT, instead of one group being wholesale deleted, the contents of the two groups should be combined.

Previously, during the call to `groupStatistics()`, the maximum of each sample would be re-discovered, so if the excluded group contained the true maximum, it could be re-discovered.

In this case, groups 10 and 11 do overlap sufficiently to be condensed into a single group, explaining how the bad ID survived:
```
grp1 <--> grp2: (4.42414, 6.40045) <--> (4.40061, 6.48312)
rtOverlap =1
```

**Comment by PMSeitzer** [comment]
The entire `reduceGroups()` method has some problems - in addition to not merging peak groups properly, there is no transitivity check - e.g., `A` precedes `B` and `C`, and if all are compared, `A` should merge with `B` and `B` should merge with `C`, but `A` compared with `C` does not result in a merge.

Probably, `reduceGroups()` should be eliminated, and a different approach for merging peak groups should be devised.

In so doing, the tricky part will be deciding when two groups ought to be merged into a single group, or when the sample-specific content of one group should be swapped/relocated to another group.

Currently, this is all done based on RT proximity.

It's important to recognize that in general, this is a very hard problem, and when people look at peak groups intuitively, they are usually adding additional assumptions like "the intensity of all groups should be about the same", or "there are clearly 2 isomers here, we should optimize to find both isomers in as many groups as possible".

It may be too much to ask to fix all peak grouping associated problems at once, as there will always be tricky cases.  At the least, however, we should try and improve a few obvious problems.

**Comment by PMSeitzer** [comment]
This is now handled by `EIC::groupPeaksD()`, which builds in `peakdetector`'s `reduceGroups()` as a part of the routine.

**Comment by PMSeitzer** [comment]
Completed as of https://github.com/eugenemel/maven_core/commit/da9b9fbc1424303a55c8b86488d3245fbc44d817
