### ISSUE TITLE
Cannot install Maven 8.1.28.6 on windows PC

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#489]
![image](https://user-images.githubusercontent.com/56043766/131186442-c52ee22e-c244-4033-b57c-edf3e8383115.png)
![image](https://user-images.githubusercontent.com/56043766/131186462-e2c550de-ce24-41da-886b-dfad66ade5bf.png)
![image](https://user-images.githubusercontent.com/56043766/131186480-5bf3cc9a-0b9c-4ac1-8160-5ce27b727b67.png)
![image](https://user-images.githubusercontent.com/56043766/131186492-2438eebb-d377-4221-a470-4273aafc81db.png)

**Comment by PMSeitzer** [comment]
Will try this with no modifications in `8.1.28.7`, if it does not work, moving to `8.1.28.8`.
