### ISSUE TITLE
How to add the KEGG library to the new edition of the  MAVEN?

### ISSUE THREAD

**Issue by Hansencch** [eugenemel/maven#497]
![image](https://user-images.githubusercontent.com/91190557/134325294-a99af43e-8816-4ccb-af60-e7ed1867ca31.png)
![image](https://user-images.githubusercontent.com/91190557/134328040-4f4d83ec-1b65-4863-bcdd-c11182f24c79.png)

**Comment by PMSeitzer** [comment]
Hey @Hansencch, thanks for your interest in MAVEN.

You can upload a new library to maven via an `.msp` file.

So, you will need the latest KEGG library formatted as an `.msp` file.

Once you have that, click the `Library` button in the main window top tool bar.  When the library dialog appears, click the `Import New Library` button and navigate to the updated KEGG library `.msp` file.  Once the library has successfully imported, the library will appear in the list.

Please feel free to reach out if you have any problems.

**Comment by Hansencch** [comment]
Thanks a lot for your help! But there is a problem that I couldn't find the KEGG library. It seems that the KEGG library already included in the MAVEN but not in the E-MAVEN.




Best,




Changhan
















At 2021-11-11 06:52:53, "Phillip Seitzer" ***@***.***> wrote:

Hey @Hansencch, thanks for your interest in MAVEN.

You can upload a new library to maven via an .msp file.

So, you will need the latest KEGG library formatted as an .msp file.

Once you have that, click the Library button in the main window top tool bar. When the library dialog appears, click the Import New Library button and navigate to the updated KEGG library .msp file. Once the library has successfully imported, the library will appear in the list.

Please feel free to reach out if you have any problems.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PMSeitzer** [comment]
Hey @Hansencch ,
I took a quick look and couldn't find the KEGG file either.  There may be a file named `KEGG.csv` in the `methods` sub-folder of your installed MAVEN directory.  If so, this must be an old version that predates my time working on the project.

Best of luck!

**Comment by Hansencch** [comment]
Thank you so much! Really appreciate your help!


Best,


Changhan
















At 2021-11-11 12:48:53, "Phillip Seitzer" ***@***.***> wrote:

Hey @Hansencch ,
I took a quick look and couldn't find the KEGG file either. There may be a file named KEGG.csv in the methods sub-folder of your installed MAVEN directory. If so, this must be an old version that predates my time working on the project.

Best of luck!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
