### ISSUE TITLE
Import/Export function for sample file setup

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#50]
![Screen Shot 2019-09-23 at 2 19 43 PM](https://user-images.githubusercontent.com/31489371/65463781-4aa85e00-de0d-11e9-8b07-d49d0c154246.png)
Creating an import/export function for file labeling, sorting and grouping where we can import pre-existing setups to new mzrollDB files. Particularly useful and time saving for large sample volumes. Differences in sample names (e.g. method M002A to M005A) could be user defined.

**Comment by PMSeitzer** [comment]
Adding to milestone, but able to move out if desired

**Comment by PMSeitzer** [comment]
Implemented as of 5c3cf9acbe6bbcf975194ea58e6602e94751b078
