### ISSUE TITLE
Sum level information in the detected features table or clamDB

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#506]
I am currently working on DIMS data, and thought it would be helpful to look at isomers if we have information of sum composition level as an additional column for the result table/bookmarks.

**Comment by PMSeitzer** [comment]
perhaps, right-click option to add columns with lipid summarization information

**Comment by PMSeitzer** [comment]
Completed as of 065d68b63a30fa1043fd35a7c0051f1388f38d9a
