### ISSUE TITLE
view MS1 of peaks on Maven

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#509]
![image](https://user-images.githubusercontent.com/56043766/141854681-9379a53f-25ee-4d37-80ef-b7becda17360.png)

I have a chromatogram of this feature. Maven annotated 1 peak with the circles, however, if I want to view the MS1 spectra of other peaks beside the main peak, Maven wouldn't let me do that. Is there anyway for me to view MS1 of any peak within the mass range?

**Comment by PMSeitzer** [comment]
The peaks are picked once the basleline drop top x is adjusted from `0%` to `60%`
