### ISSUE TITLE
Adding novel compound to (extra) library for validation.

### ISSUE THREAD

**Issue by tobimaile** [eugenemel/maven#51]
Sometimes compounds are detected for which no in-house library entry exists and/or no MS2 is available online or just experimental MS2 are available.
E.g. putative hit on Phenylsulfate, for which a matching experimental MS2 exists on HMDB, but a standard would be needed for validation (see screenshot):

![Screen Shot 2019-09-23 at 3 04 56 PM](https://user-images.githubusercontent.com/31489371/65466587-2bf99580-de14-11e9-8c6e-a9a651af3fa5.png)

It would be great to have a save function for clean MS2s found in Maven where the data would be saved in a central "experimental library" from which we can pull data for validation of new compounds.

**Comment by PMSeitzer** [comment]
As a starting point, this could generate a faux msp entry from a record, which could be then be reloaded into MAVEN.  A right-click menu option could be "Create MSP Entry", which could launch a dialog box containing a text box with the msp information.

**Comment by PMSeitzer** [comment]
Waiting until this feature is requested by someone else.

**Comment by PMSeitzer** [comment]
This was implemented via the "Copy Spectrum to Clipboard Options" #562
