### ISSUE TITLE
mzkitchen doesn't pick up the real peak

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#520]
Similar to one of the bugs last year. Mzkitchen data doesn't pick up the real peak, but only reporting noises

These are the two suggested peaks from mzkitchen:
![image](https://user-images.githubusercontent.com/56043766/149550289-16d94312-8281-46b7-bd4b-a65bf2279025.png)

![image](https://user-images.githubusercontent.com/56043766/149550336-09b4c166-1cf1-4aaa-8f3b-f1aabb5d7e92.png)

The real peak is the base peak located next to it.
![image](https://user-images.githubusercontent.com/56043766/149550500-10e6a527-cd84-4ff1-bbf0-2606f0b1e56f.png)

**Comment by PMSeitzer** [comment]
hi @ngoccalico, which version of mzkitchen were you using? I think it would need to be the current version (`21b`), otherwise you may be seeing a repeat of the same bug from last year.

**Comment by PMSeitzer** [comment]
Hey @ngoccalico, did we ever resolve this bug?

**Comment by ngoccalico** [comment]
Yes we did
