### ISSUE TITLE
Unexpected slowdowns in 8.1.0 as compared to 8.0.12

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#53]
Probably b/c of peak grouping in EIC widget, with the new peakgroups algorithm B being very slow.

May want to adjust thresholds / turn this off, or put in a background thread.

This is a bigger issue when there are a lot of samples, owing to the `O(N*N)` complexity of the dissimilarities

**Comment by cmsand** [comment]
Experiment X0120-M004A is a good example of this. m/z range of 540.5053-540.5086 is some background noise that has lots of peak groups. Takes several minutes to load the EIC of this mass range in Maven 8.1.0 and loads instantly in version 8.0.12

![image](https://user-images.githubusercontent.com/9013133/65981405-df264800-e42d-11e9-8d1a-4ff7c75eef45.png)

**Comment by PMSeitzer** [comment]
This was a result of `EIC::groupPeaksB()`.  This has been changed to `EIC::groupPeaks()`, fixing the problem.
