### ISSUE TITLE
Isotopes gui missing isotopes

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#536]
When I clicked on a peak group it didn't generate a new list of isotopes under the isotopes widget. However, typing chemical formula or changing the adducts refreshed it. The isotope plots looked strange for some compounds but not all.

**Comment by PMSeitzer** [comment]
This is probably a GUI updating bug. Just need to ensure that things are refreshing properly.
see data in linked folder:
https://drive.google.com/drive/folders/1Q8-H9Y2sEp3BB7Sy0X_rzXHupOboCAx6

**Comment by PMSeitzer** [comment]
Not sure what this is about - pushing off to next milestone. Need to follow up with @ngoccalico

**Comment by PMSeitzer** [comment]
This was originally a design decision, not a bug, but the behavior has been changed to match user expectation.
Completed as of 9213eb669ab6d964c407c2b90eccebe72edf6b85
