### ISSUE TITLE
Updates to support additional information in SRMTransition (GUI, peakdetector)

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#564]
Sometimes, in addition to a `precursorMz` and ` productMz`, `SRMTransition`s may also have a `transitionId` number.  In that case, these transitions should be split out into different groups.
This has largely bee updated for peakdetector, but has not been corrected in the MAVEN gui.

**Comment by PMSeitzer** [comment]
After updating to Protewizard version `3 0 22252 f9ce728`, much more information is available in the srmId string:
```
 <chromatogram index="2" id="- SRM SIC Q1=295.3 Q3=195.2 sample=3 period=1 experiment=1 transition=0 ce=25 name=12(13)-EpOME (295/195)" defaultArrayLength="2094">
```

**Comment by PMSeitzer** [comment]
specifically, should take out `ce=` and `name=` with regex.

**Comment by PMSeitzer** [comment]
Completed GUI updates for new `SRMTransition` protocol as of b8077fdf0b647b1006186562a69a02726e25bb41

**Comment by ngoccalico** [comment]
Feedbacks on running 1st QQQ metabolomic pilot
Transition file: https://drive.google.com/open?id=1aDybSyRnUKd3LLOWavztsIYHkiVURTd8&authuser=ngoc%40calicolabs.com&usp=drive_fs

mzML directory: Z:\7500\mzML\Metabolomics_NV\Sciex_auto_convert_2022

1. mzML conversion ran successfully on QQQ pc. Q: How can we have each wiff file generate its own folder?

**Comment by ngoccalico** [comment]
Feedbacks on running 1st QQQ metabolomic pilot on Maven:

- Opened QQQ mzML scheduled with Maven 2.0.2 with the library imported
- Can browse through list of compounds in the library, however, cannot run peak detector automatically

-For the Calico QQQ server, how do we import library, and initiate the automated peak detector?

@PMSeitzer

**Comment by PMSeitzer** [comment]
This work will now be handled in #568
