### ISSUE TITLE
peak grouping for LC lipidomics

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#574]
![image](https://user-images.githubusercontent.com/56043766/198398708-3d7baa78-6945-4d8b-9ca0-c674f92fd207.png)

Noticed an abundant ID didn't get assigned as good, after investigating,  mzkitchen didn't extract the compound correctly. A similar issue was observed in the past with amino acids. 

Project X0229-M004B can be found under met_dataset.

**Comment by ngoccalico** [comment]
![image](https://user-images.githubusercontent.com/56043766/198402237-e45237ed-85b1-48e6-b3a1-8d32fdebbe23.png)

**Comment by PMSeitzer** [comment]
Need to follow up with @ngoccalico  to check status of this case.

**Comment by PMSeitzer** [comment]
The problem appears to be confined to one specific dataset, so not fixing (at least for now).
