### ISSUE TITLE
MS1 Scans List Painfully slow

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#583]
MS1 Scans List is painfully slow. A simple solution to this problem is to add more filters up front, such as only constraining to one sample at a time, or one rt range at a time.

Similarly, there may be some issues with respecting visible scans, .e.g the arrow keys in spectra widget doesn't appear to really respect visible scans

**Comment by ngoccalico** [comment]
adding myself to this issue.

A recommendation of having an option of choosing which sample to show the MS1 besides browsing through the MS1 scans list, which killed my ram quickly.

**Comment by PMSeitzer** [comment]
Completed as of 62e4fb453584c3cea07546d4d4e54d2d8c11b5d5
