### ISSUE TITLE
Peak detection finds 0 groups

### ISSUE THREAD

**Issue by bwilde89** [eugenemel/maven#590]
I have tried on both Mac and Windows to use the peak detection function and it always comes back with 0 groups. I have adjusted the settings ad nauseam but without success. I have also followed along with the YouTube tutorial and used the exact same settings used there. I am using mzXML files.

**Comment by PMSeitzer** [comment]
Hi @bwilde89 , thanks for letting me know.  Did you have a library loaded? If you don't, you'll need to check the box that says `Retain Peak Groups that do not match to compounds`

![Screen Shot 2022-12-01 at 10 10 10 AM](https://user-images.githubusercontent.com/1757701/205128608-69d9b237-f607-4a6c-aba6-0a1e190ee2b1.png)

If your samples do not contain MS2 scans, you will also need to uncheck the box that says `Must Have MS2`

![Screen Shot 2022-12-01 at 10 11 49 AM](https://user-images.githubusercontent.com/1757701/205128785-0e7d1901-c376-4107-b6fc-e5a3cd5162cb.png)

I hope this helps. Sorry for your trouble. If that doesn't work, feel free to provide more information, including a link to one or more of your mzXML files (if you are able to share them).

**Comment by PMSeitzer** [comment]
Hi @bwilde89 Could you let me know if this did or did not work for you?

**Comment by bwilde89** [comment]
Thanks so much for the quick reply and the helpful suggestions. It did work.
