### ISSUE TITLE
Options dialog sometimes showing empty

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#60]
Inexplicably, sometimes the dialog shows as empty. Seems to only happen when multiple samples are loaded.

**Comment by PMSeitzer** [comment]
I was unable to reproduce this issue on my system, did find some previous reports of this bug:
https://stackoverflow.com/questions/23106731/qdialog-is-blank-with-show-command
https://forum.qt.io/topic/83179/qdialog-don-t-show-widgets-when-method-show-calling

**Comment by cmsand** [comment]
Happens to Library Manager dialog as well. However, opening Options or Library Manager dialogs don't register through the terminal (only Direct Infusion does), so there's no readout. 

No idea what triggers this. Seems to only happen on Maven instances I've had open for a while (a couple hours at least), and restarting Maven fixes problem. 

<img width="1002" alt="Screen Shot 2019-10-21 at 8 13 55 PM" src="https://user-images.githubusercontent.com/9013133/67257252-e2ff2600-f43f-11e9-872c-41956717186c.png">

**Comment by PMSeitzer** [comment]
This appears to happen to all of the dialogs. Unrelated to showing message in console.

**Comment by PMSeitzer** [comment]
Unable to reproduce, so moving from `8.1.13` to `8.1.15`

**Comment by PMSeitzer** [comment]
This may have been fixed when we updated the travis configuration options.  If the bug is not observed in a while, will close.

**Comment by PMSeitzer** [comment]
Potentially fixed by upgrading `Qt` in travis build
