### ISSUE TITLE
Crash after loading mzML files associated with mzrollDB

### ISSUE THREAD

**Issue by brysonbennett** [eugenemel/maven#600]
Using Maven 2.0.3, it consistently crashes when loading the mzML after opening mrrollDB.  It appears to get through loading all the files, but in processing post loading is crashing somewhere.  Here are the last few lines of output:

doSegmentedAligment: X0200_M012A_std016C_p01B_A06_003_1.mzML	corrected=5275
doSegmentedAligment: X0200_M012A_std016C_p01B_A07_109_1.mzML	corrected=5230
doSegmentedAligment: X0200_M012A_std016C_p02A_A06_003_1.mzML	corrected=5224
doSegmentedAligment: X0200_M012A_std016C_p02A_A07_109_1.mzML	corrected=5171
doSegmentedAligment: X0200_M012A_std016C_p03A_A06_003_1.mzML	corrected=5250
doSegmentedAligment: X0200_M012A_std016C_p03A_A07_109_1.mzML	corrected=5165
ProjectDB::loadSearchParams()...
Search Table Names:
entry= "peakdetector"
entry= "clamDB"
End Search Table Names.
Created tables for search results.
Cleared loaded peak groups.
zsh: segmentation fault  ./Maven

The files load fine when opened directly, without opening the mzrollDB

**Comment by PMSeitzer** [comment]
@brysonbennett Thanks for letting me know. Which mzrollDB was the problem?

**Comment by brysonbennett** [comment]
X0200-M012A_first_3_plates.mzrollDB

**Comment by PMSeitzer** [comment]
see mzkitchen met_datasets

**Comment by PMSeitzer** [comment]
Could reproduce the bug, but the issue isn't super high-priority at the moment.
