### ISSUE TITLE
Maven 2 crashes when importing data on Linux/Windows

### ISSUE THREAD

**Issue by Unimelb-Vinz** [eugenemel/maven#601]
We currently experience a lot of crashes with Maven 2.0.3 usually when importing files.

We use Maven on Linux and use mzML files converted from Thermo’s .raw using proteoWiz’s conversion tool.
The files do import properly into ElMaven.

I am happy to share files or anything needed.
Files are between 200 and 600 megabytes.

**Comment by PMSeitzer** [comment]
Hey @Unimelb-Vinz, thanks for letting me know. 
Can you somehow make the mzML files available to me, so I can try it out myself? if you could write up a few "steps to reproduce", I'll see if I can reproduce the problem on my end.

Are you able to run maven with the console, so you can paste a log report into this ticket?  You can usually right-click on the icon and select "show package contents". When you launch maven, a black console window will appear with log information. Once MAVEN crashes, there should be some information in that log report.

If you need to make files available to me, you can share with my gmail phillipseitzer _at _ gmail

**Comment by PMSeitzer** [comment]
<img width="1679" alt="MAVEN2_working" src="https://user-images.githubusercontent.com/1757701/210417937-72f50dc1-8a2d-4681-b0a7-174992fa9ad7.png">

Hi @Unimelb-Vinz, it looks like I was able to open MAVEN successfully on my computer.

If you right-click on the MAVEN icon, there should be an option called "show package contents". From there, you can  select the maven executable.  When you run maven this way, a window will appear showing console output.  Would you mind trying to open one of your files using maven launched with the console?  When MAVEN crashes, the console will record some log output that will be useful for me to help me diagnose the problem.
<img width="407" alt="show_package_contents" src="https://user-images.githubusercontent.com/1757701/210418699-32665454-7e34-4bcd-99d6-95a99966b350.png">

<img width="181" alt="maven_executable" src="https://user-images.githubusercontent.com/1757701/210418711-8487a3ca-e59a-43be-9556-6a9a1cbd5141.png">

I noticed that the data appears to be collected in profile mode.  Are you able to generate mzMLs with centroided scans?  I typically use proteowizard to convert RAW files to mzMLs, centroiding all scans (use the option vendor peakPicking 1-)

Finally, are you able to try to view your data on a different operating system, say, mac os x or windows? If the problem appears to be specific to linux, that would be useful information to know.

Thanks for your patience as we work through these problems.

**Comment by PMSeitzer** [comment]
Should resolve this issue before releasing `2.0.4`, `TODO`: need to test on linux

**Comment by PMSeitzer** [comment]
As a part of this work, implement logging:
https://stackoverflow.com/questions/15025500/maintaining-a-log-file-for-a-session-for-an-application-developed-in-qt

**Comment by PMSeitzer** [comment]
This has been verified in windows, and has been reproduced in the Qt Creator IDE:

<img width="1548" alt="reproduce_issue_on_windows" src="https://user-images.githubusercontent.com/1757701/213832340-e342264f-c9cf-447f-976a-54fb80bcec04.png">

**Comment by PMSeitzer** [comment]
This was probably caused by not defining the `ZLIB` compiler flag, and then trying to decode a compressed binary array. `ZLIB` was always being defined for mac but not for windows, this has been updated as of https://github.com/eugenemel/maven_core/commit/55d80a71728521ee3984cd465916a985189f154a

**Comment by Unimelb-Vinz** [comment]
> Hey @Unimelb-Vinz, thanks for letting me know. Can you somehow make the mzML files available to me, so I can try it out myself? if you could write up a few "steps to reproduce", I'll see if I can reproduce the problem on my end.
> 
> Are you able to run maven with the console, so you can paste a log report into this ticket? You can usually right-click on the icon and select "show package contents". When you launch maven, a black console window will appear with log information. Once MAVEN crashes, there should be some information in that log report.
> 
> If you need to make files available to me, you can share with my gmail phillipseitzer _at _ gmail

Hey mate,

Sorry, was a bit of a holiday delay here.

A) I could not find a way to start Maven as command line version.
But I can definitely send you the files.

Also, we are using PIWZ converter to make the mzML files but I don't see an option to just make them as centroid from the collected profile data.

We also found a way to make it not crash by putting in 0 for the m/z when loading the data. It seems MAVEN just doesn't access all the RAM that is available to it.?

**Comment by PMSeitzer** [comment]
@Unimelb-Vinz No problem. Another user also had trouble loading data, and after some investigation I was able to reproduce the bug and fix the problem.  You can get the new release that fixes the bug [here](https://github.com/eugenemel/maven/releases/tag/2.0.5). Hopefully it's the same problem, and the new release works.

If the new release doesn't fix the problem, you can send me one of your files that is causing the issue. You can reach me at phillipseitzer _at_ gmail. ~Phil
