### ISSUE TITLE
Can not find raw data files in Metabolights

### ISSUE THREAD

**Issue by clzani** [eugenemel/maven#604]
In the R example is stated:
These files may be retrieved from the Metabolights online database, accession number MTBLS3097

However, a search for this study retrieves nothing. Are they accessible from another place?

**Comment by PMSeitzer** [comment]
Hi @clzani thanks for letting me know.
I'll reach out to metabolights and see why they haven't released the study. Alternatively, I'd be happy to share the files with you via googledrive if you send me an email at phillipseitzer _at_ gmail
Another person had the same problem about 3 months ago, and in that case, I was able to send them everything over google drive.

**Comment by clzani** [comment]
Hi @PMSeitzer thanks for the prompt reply! I sent you an e-mail as requested. best regards

**Comment by PMSeitzer** [comment]
Hi @clzani apologies, I seem to have lost track of this work. Could you send me an email again?
