### ISSUE TITLE
MAVEN crashes while loading in compound list

### ISSUE THREAD

**Issue by sevahn** [eugenemel/maven#607]
Hi there, I downloaded the latest MAVEN version (2.0.5) .

(1) When loading in the compound list compoundlist.csv , the program abruptly crashes.
I've attempted this multiple times to no avail.

(2) Also - when I try and load in my own database, like the one linked at the bottom of this post, https://github.com/ElucidataInc/ElMaven/issues/579), the program isn't seeing the 'csv' file

Please advise! many thanks!

**Comment by sevahn** [comment]
I'm getting the same issue with 2.0.4 - what's a good release to use? many thanks!

**Comment by PMSeitzer** [comment]
Hey @sevahn thanks for letting me know about the issue. I recovered your file and I was able to load the csv files on my version of MAVEN. Unfortunately, MAVEN did not crash for me.
Can you include the debug console message in this ticket?
Can you provide some more information about your system (operating system, version, etc)?
Thank you!

**Comment by PMSeitzer** [comment]
Here is what the loaded compounds look like on my system:

![loaded_compounds_widget](https://user-images.githubusercontent.com/1757701/214630683-fff3ce4e-08e0-40c1-8310-284eca2ba6a5.png)

**Comment by sevahn** [comment]
thanks for your fast response and for supporting this software. 
i realized the error is that compoundlist.csv is a template and is empty, i was mistaken this was KEGG.

would you be able to attach the CSV of KEGG that comes with older versions like 2011.16.1?

**Comment by PMSeitzer** [comment]
@sevahn Are you referring to [this file](https://github.com/eugenemel/maven_core/blob/master/bin/methods/KNOWNS.csv)? There are some kegg ids included.

**Comment by sevahn** [comment]
@PMSeitzer I am referring to the very long list under 'KEGG' in, say, Windows version 2011.6.17

**Comment by PMSeitzer** [comment]
@sevahn I'm not sure what file you're referring to - I only started working with MAVEN in 2019. There is an older repo dating back to the 2011 era, but I don't know anything about that work, or if it is being maintained, etc.
Here is a link to help get you started:
http://maven.princeton.edu/index.php?show=download
