### ISSUE TITLE
Covariants widget not working

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#613]
The covariates widget, which should show coeluting peaks, does not appear to be working any more.

**Comment by ngoccalico** [comment]
I recalled the function was working in version 8.1.28.28.13. Maybe it worked in version 2.0.0-- not sure about it. In version 2.0.3 it stopped working.

**Comment by PMSeitzer** [comment]
Reenabled covariants widget as of 1519f0da312841994a1eb028ea14f665b82f40e2
