### ISSUE TITLE
No MS1 Targeted Groups Detected

### ISSUE THREAD

**Issue by grangel0955** [eugenemel/maven#632]
I am using Maven 2.10.1 on Mac OS Ventura 13.2. My goal is to use Maven to do a targeted library search on MS1 data (no MS2 collected), and manually go through the EICs and mark peaks as good or bad. However, when I try to do either a Peak Detection or a Library Search, no groups are detected at all using the built-in KNOWNS.csv library or my own .csv library (see screenshots of parameters used). Interestingly, when I click on the compounds in the "Compounds" widget, the EICs pop up and the on-the-fly quantitation of peak area finds potential peaks. 

We typically use El Maven for this purpose (on Windows machines), but would like to move to Maven, since El Maven is no longer being supported by Elucidata. 

Any help with this would be greatly appreciated! 

![Screenshot 2023-04-27 at 11 19 25 AM](https://user-images.githubusercontent.com/43796470/234908839-16c8eeba-cfdb-4d0e-838d-409ad80a0098.jpg)

![Screenshot 2023-04-27 at 11 21 25 AM](https://user-images.githubusercontent.com/43796470/234909300-47252969-64a6-431c-bef5-24d2dc944c99.jpg)

**Comment by PMSeitzer** [comment]
Hey @grangel0955 Thanks so much for your interest in MAVEN. Would it be possible for you to attach some sample files, so I can try to reproduce your case?

You can send the info to maven2software _ at _ gmail [dot] com

**Comment by PMSeitzer** [comment]
@grangel0955 Okay, I figured out the problem:
MAVEN has become increasingly MS2-focused, and it looks like this has resulted in some user experience issues for MS1-only users.
There is a parameter to control the minimum number of MS2 fragments that must be matched to retain a compound identification.  By default, this is set to `1`.  For MS1-only data, this will always be `0`.
Here is how you can change this parameter:

1. Open the `Library Search` via `Widgets -> `Library Search`.
2. Switch to the `Peak Scoring` tab.
3. Find the `MS/MS Matching Scoring Settings` button in the dialog.

<img width="713" alt="Peak_Scoring" src="https://user-images.githubusercontent.com/1757701/235219040-1b021658-a1a7-4768-b375-58655576eae6.png">

5. Click this button, which will launch an additional dialog.  If the dialog that pops up, The first field is `Spectral Matches`. By default, this is set to `1`.  Change this value to `0`. Click `OK` to close the dialog.

<img width="508" alt="MSMS_Scoring_Settings" src="https://user-images.githubusercontent.com/1757701/235219079-319b3938-450f-44c6-9c19-c400d7585f0b.png">

That's it.  After making this change, I was able to find many compounds in your data using the Library Search.

I think the default set of parameters are a bit too loose for this data.  I spent some time exploring the parameters, and found that a looser set gave fewer candidates.  Here is an example of a stricter set that gave about ~200 results:

<img width="835" alt="Strict_Parameters" src="https://user-images.githubusercontent.com/1757701/235219763-d7c5a1bd-1b37-4ef1-90bc-384e13e69382.png">

Hope this helps. Let me know if you encounter any more issues or have any more questions!
