### ISSUE TITLE
Update TAGS.csv and parsing

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#636]
Add ability to specify order of tags
Add 6 more tags (open slots)
Update `TAGS.csv` with QQQ-specific info.

**Comment by PMSeitzer** [comment]
Updated `TAGS.csv` as of fa53462a6abff5f1844b690c272fa95f8cf9333c
Need to review with the group before closing this ticket.

**Comment by cmsand** [comment]
Team decision on tags from 5/10/23 meeting: 

revisit
good
bad
reassign compound name
Internal standard
Annotated from external source
Compound of interest / Plotting
Major adduct
Fragmentation for sn1
Fragmentation for sn2

**Comment by PMSeitzer** [comment]
Completed as of https://github.com/eugenemel/maven_core/commit/a742d69b858a9e0fd5b5c67cf49415a0724372e1
