### ISSUE TITLE
Extend "Delete Labeling" to Isotopes in Maven Export

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#69]
Currently, when exporting bookmarks from Maven all deleted bookmarks are still exported, but marked with an "x" in the label column. However, this label does not extend to isotope reporting which makes filtering that isotope data difficult. It would be useful to mark _all_ deleted data with an x so it can be easily filtered out programatically.

**Comment by cmsand** [comment]
Exporting CSV Bookmarks in Maven 8.1.11
Data File: X0131-M002A-08_Std002A.mzML

Create bookmarks: Turn isotope Detection on through Options menu. In m/z search window, search compound formula C9H11NO2 and bookmark peak twice. Then in bookmarks pane delete one of the duplicated bookmarks grouped. 

Export bookmarks: Select "Export Groups to Spreadsheet" in bookmarks pane. Select Export All Groups and save as a "Group Summary Matrix Format Comma Delimited."

**Comment by PMSeitzer** [comment]
Implemented as of `a45aad0345051788713ed31ec71cb3777ac57db6`.
