### ISSUE TITLE
CLOSE FIGURED IT OUT

### ISSUE THREAD

**Issue by EricLuo12** [eugenemel/maven#696]
My Maven (version 2.10.9) is crashing whenever I imported a new library. The library I am uploading is only 58 KB, but keeps crashing whenever I use it. I run a windows 11, 3.20 ghz computer and what comes up on the screen with the code is 

Database: unloadCompounds(): initial= 0 removing 0 retaining 0 (removed+retained) 0
delteCompoundsSQL "NameOfList"  0

And then it immediately crashes.

**Comment by PMSeitzer** [comment]
Thanks for letting me know @EricLuo12 - Can you attach the library file here?

**Comment by PMSeitzer** [comment]
@EricLuo12 Glad you figured it out.
