### ISSUE TITLE
Possible bug: Program crashing after click "sample alignment."

### ISSUE THREAD

**Issue by rmokry** [eugenemel/maven#698]
I am analyzing lipidomic data. I load a compound list, load my sample files, and then click "sample alignment." The program closes along with terminal after clicking "sample alignment." I have tried loading different compound lists and different sample files. All individuals in the lab that work on different computers are experiencing this issue when attempting to align the samples.

**Comment by PMSeitzer** [comment]
@rmokry Thanks for bringing this to my attention. The "sample alignment" code is very old, and hasn't been used in a long time.  There are some new RT alignment approaches that have been developed, I've always applied them outside of the GUI.
I'll see about incorporating these new RT alignment approaches into the GUI, and let you know what I find.
Would it be possible to include some data with this ticket, so I can reproduce your bug?

**Comment by PMSeitzer** [comment]
Fixed the crash as of fee8b6405a08e790888de42fcbc1ff52dd42408c, but the alignment doesn't seem to be doing anything. Consider updating this dialog with more modern approach.

**Comment by PMSeitzer** [comment]
Reworking dialog on `issue-698`, basic functionality appears to be working as of 2bcd8a9bc9460f0d34d98d938d69f196a9b4ede8, however, encountered a bug in the RT alignment code, Need to fix this bug/perform more testing before releasing this feature.

**Comment by PMSeitzer** [comment]
This work has been completed and merged into `master` - new, alternative RT alignment dialog is now available.
@rmokry The updated code/dialog will be available in the next release (will try to release by the end of the week).

**Comment by rmokry** [comment]
Thank you for this update! I appreciate the work.

From: Phillip Seitzer ***@***.***>
Sent: Wednesday, January 24, 2024 12:09 PM
To: eugenemel/maven ***@***.***>
Cc: Mokry, Rebekah - (rmokry) ***@***.***>; Mention ***@***.***>
Subject: [EXT]Re: [eugenemel/maven] Possible bug: Program crashing after click "sample alignment." (Issue #698)


External Email

This work has been completed and merged into master - new, alternative RT alignment dialog is now available.
@rmokry<https://github.com/rmokry> The updated code/dialog will be available in the next release (will try to release by the end of the week).
