### ISSUE TITLE
MS1 Peak Detection Crash

### ISSUE THREAD

**Issue by Progress109** [eugenemel/maven#699]
We load our samples and library into MAVEN2, then the use "Peak detection" tool with the only difference from the default settings being that we uncheck the "Must have MS2," this seems to cause MAVEN2 to crash. We have tried this will multiple libraries, with and without samples that contain MS2 data, and with different Peak Detection settings, which all resulted in the Progress Bar jumping to 20%, freezing, and eventually crashing. Help would be greatly appreciated!

**Comment by PMSeitzer** [comment]
Thanks for letting me know, @Progress109 . Can you provide a couple of `mzML` files and libraries, so that I can reproduce your bug?

It would also be helpful to know what system you are using, (e.g. Windows, mac os, linux), as well as the version of MAVEN you are running.

**Comment by Progress109** [comment]
Sure thing! I have tried both on mac os (version 2.10.10) and windows (version 2.10.10). I have attached the MS1 library used, but I don't think that GitHub supports attaching mzML or RAW files, so I am not sure how to get these to you. Thank you for your help and please let me know what else I can do!

[240111_Positive_Instrument_Specific_Spectral_Library.csv](https://github.com/eugenemel/maven/files/13941185/240111_Positive_Instrument_Specific_Spectral_Library.csv)

**Comment by PMSeitzer** [comment]
@Progress109 Thanks for letting me know. I tried out your library against some samples that I have, and it looks like MAVEN worked on my end. Perhaps there is something about your files?
If you send me an email at [maven2software@gmail.com](mailto:maven2software@gmail.com) with a link to your files, I can try it out.
