### ISSUE TITLE
Change csv output to area

### ISSUE THREAD

**Issue by toniSon** [eugenemel/maven#705]
Is there a possible way to change the values in detected features to area / areaTOP and to change the output values in .csv? In the newest version (2.10.13) it is not possible.

Thank you for the great software!

**Comment by PMSeitzer** [comment]
Hi @toniSon,
Thanks for your interest in MAVEN.
You can change the values of the currently displayed quant type:
![MAVEN_select_quant_type](https://github.com/eugenemel/maven/assets/1757701/501ee477-a89a-4ce2-b1a9-3dea6419d3ed)

When you export a report from a Detected Features table in MAVEN, there will be a series of columns named `<sample_name> (Intensity)`.  The intensity that is exported is the same as the one that is the currently selected quant type.  If you change the currently selected quant type, you will change what is exported.

**Comment by toniSon** [comment]
Ah, thank you!
That was quite confusing, as I thought the Intensity is only the height.

Thank you for your program!
