### ISSUE TITLE
Isotope export with multiple Isotopes

### ISSUE THREAD

**Issue by toniSon** [eugenemel/maven#709]
When you export the list of isotopes, it exports not only those you selected (e.g. C13) but includes e.g. N, O and S as well. This is then calculated into the fraction as well, and the percentages for only the C fractions are off.

**Comment by PMSeitzer** [comment]
@toniSon thanks for bringing this to my attention. 
Can you tell me more about how you observed this bug? Specifically, I'm wondering how you generated the list of isotopes. In general, you should try to get the program to a state where you are only observing the isotopes that you want, and the export should include only those isotopes.

The more information you provide, the faster I can deliver a solution to you!

**Comment by PMSeitzer** [comment]
@toniSon My suspicion is that the export is including the natural abundance isotopes - which you can change via a check box:
<img width="235" alt="Screenshot 2024-04-24 at 11 05 36 AM" src="https://github.com/eugenemel/maven/assets/1757701/09bdf3bd-e8b1-4960-afe9-779ab23013e4">
