### ISSUE TITLE
Viewing Peak Area integrated in User Interface

### ISSUE THREAD

**Issue by Progress109** [eugenemel/maven#713]
Hi, I was wondering if there is a way to view the Peak Area that is being integrated in the MAVEN User Interface outside of when I change the EIC legend to "Area," i.e. is there a way to actually see (maybe by it being filled in) what area is being integrated? It would be very useful, since this would inform whether or not manual peak integration is required.
Thanks in advance!

**Comment by PMSeitzer** [comment]
@Progress109 This feature used to exist, but it was removed b/c mzrollDB files don't save enough information to reproduce the display.
What you can do is show the RT bounds of a peak using the "Display peak group RT range on click":
<img width="1109" alt="peaks_options" src="https://github.com/eugenemel/maven/assets/1757701/db969d29-033e-4ad5-b2d7-218d70d4afb2">

If you manually integrate peaks, after you manually integrate, it will show the selected area for quant.

You can display EICs as filled or hollow by clicking the "Show Filled EIC" button in the EIC widget (button with blue Gaussian curve, top center toolbar).

Hope this helps - let me know if this works for you!

**Comment by Progress109** [comment]
@PMSeitzer thank you this solved it!
