### ISSUE TITLE
Win Exe missing for vers 14

### ISSUE THREAD

**Issue by toniSon** [eugenemel/maven#719]
Hi!
I just wanted to say, that the windows exe is missing for the newest version. I would be happy to try it!

Thanks for the update!

**Comment by PMSeitzer** [comment]
Completed as of 1d6002cd00222ce3fe00d98487ae49c3e40e1c6f
@toniSon Apologies for the bad build! I was able to track down the problem and produce the windows build.

You can find a new windows build here:
https://github.com/eugenemel/maven/releases/tag/2.10.14.c
