### ISSUE TITLE
Compound Search list disappears when selecting MS2

### ISSUE THREAD

**Issue by tobimaile** [eugenemel/maven#81]
The hits in the Compound Search list window disappear when selecting MS2 events for matching (see attached Quicktime movie). This is a rare event and I found a workaround by selecting different PPM settings in the Precursor PPM input field. Interestingly, going the same in the Fragment PPM input does not do anything.

[Bug-MS2.mov.zip](https://github.com/eugenemel/maven/files/3827989/Bug-MS2.mov.zip)

**Comment by PMSeitzer** [comment]
In `point.cpp::mousePressEvent()`,
```
    if(_scan) {
        _mw->fragmenationSpectraDockWidget->setVisible(true);
        _mw->fragmentationSpectraWidget->setScan(_scan);
        _mw->massCalcWidget->setFragmentationScan(_scan);
...
```
The `_mw->massCalcWidget->setFragmentationScan(_scan);` should have worked.  The `setFragmentationScan()` method in turn calls `showTable()`, which should update the table.

Whenever I have tested this, it has worked properly.  However, I have seen some strange behavior with the EIC plot, where sometimes it inexplicably crashes, getting lost in one of the `mouseMoved()` / `mouseRelease()` / mouse controller methods.

I am concerned that these strange crashes I have seen may be putting the program in a strange state, which is causing the issue. In that case, the problem would simply be that the update is never triggered.

I think the problem may be in `EICPoint::hoverEnterEvent(QGraphicsSceneHoverEvent*)`. I have added a debug statement there.  However, until I see the behavior again (or have a reproducible example, I don't think it is worth debugging this now).

**Comment by PMSeitzer** [comment]
I've added some new debugging statements as of `69fb77cf5a744fea2975073f3e6c989b0eb2fa48`. I think the best thing to do now is to release `8.1.15` without this bug fixed, and the next time it appears, I'll have more information to be able to diagnose and fix the problem.

**Comment by PMSeitzer** [comment]
Moving out of this milestone, as no new information has emerged.
