### ISSUE TITLE
exporting the peakwidth in Maven

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#83]
From the bookmark, I exported the data out in the csv form, however, I couldn't obtain any information about the peakwidth. Could you add this function in?

Thanks!

**Comment by PMSeitzer** [comment]
Hi @ngoccalico, Did you want the peak width of the entire group, or the peak width of each individual peak?

I could also include the values that I would use to calculate these values.
So, we could add any / all of the following:

1. `mzmin`
2. `mzmax`
3. peak width (`mzmax - mzmin`)
4. `rtmin`
5. `rtmax`
6. peak length (`rtmax - rtmin`)

Anything else while I am looking at this part of the code?

**Comment by ngoccalico** [comment]
Hi @PMSeitzer, I think the value #6 you listed should be used to calculate it. Based on how the peak was picked, we can roughly estimate the peak width according to the picture attached here. 
![image](https://user-images.githubusercontent.com/56043766/68883144-4ab63300-06c5-11ea-8174-2ae61848cdc0.png)
and I just want the peak width of each ID. For example, a group contains 5 samples with 25 ID, I want to extract out the 25 peak width, with each one belongs to different ID. I hope it helps! thanks!

**Comment by PMSeitzer** [comment]
Implemented as of 16d37cfcdfe288ba8a08d381fb9ba3132d54fe8b
RT bounds are determined based on the local minima found between local maxima. If no local minima are found, goes to the edge of the window.
