### ISSUE TITLE
Add feature: Bookmark window zooming to latest metabolite after import

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#86]
Would it be possible to have the bookmarks window zoom automatically to the current imported metabolite from rumsDB or Detected Feature windows? Would this be possible regardless of which filters are set (e.g. MS2 score or m/z selected in the bookmarms window)?

Cheers,

Tobi

**Comment by PMSeitzer** [comment]
It is possible to have the bookmarks window select the new entry after the group has been added, if the added group respects current filters.

The row in the bookmarks table corresponding to the new bookmark would show as selected, and the table would scroll to the current row.

**Comment by PMSeitzer** [comment]
Implemented as of a7a97d2cc7c84cc1e3c76bca077de610300c94ec
