### ISSUE TITLE
Issue identifying dual 13C/2H labeled peaks

### ISSUE THREAD

**Issue by lparsons** [eugenemel/maven#9]
Maven (old version) seems able to identify peaks that are isotopes with either 13C or 2H, but does not seem able to pick up any peaks that contain 13C and 2H combined.

I'm gathering information and sample data so I can reproduce this issue using the updated code. I'll update this issue as I get more details, etc.

**Comment by lparsons** [comment]
It looks like this combination of isotopes is simply not scanned for (see code at https://github.com/eugenemel/maven_core/blob/f83a1634f8b9f549575f5e9ac4d9af3634aa327f/libmaven/mzMassCalculator.cpp#L194). @eugenemel Do you see any issues with simply adding some code to simply check for C+H isotope combinations? Once I get some example data (still waiting) and I have a bit of time, I'll try it and see how it goes.

**Comment by eugenemel** [comment]
You are right, isotopes with both C13 and 2H are not computed. I don't recall every implemented this, so I am curious how it was working before? May be I did and forgot.. anyhow, lets add the  loop to calculator and see how it goes.

**Comment by lparsons** [comment]
Sorry, I didn't mean to imply it did ever work, I suspect it did not. It's just that now, it's needed. I'll go ahead and add the code and try to test it out.

**Comment by lparsons** [comment]
This issue was addressed in 6a5e0892f6022adb8f9341de0870fc71ffac24a7.
