### ISSUE TITLE
Chemical Formula Text Search search doesn't recognize chemical formulas with less than 2 Carbons

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#90]
Chemical Formula Text Search only displays EICs of chemical formulas with 2 or more Carbons. Searching by M/Z always works though.

For example, searching the chemical formula of acetic acid (CH2O2) or phosphoric acid (H3PO4) will not display EICs. Searching their respective M/Zs (44.99765, 96.969) does display EICs. 

Any chemical formula with at least 2 Carbons (e.g. C2H4O2) can be searched by chemical formula with no issues.

**Comment by PMSeitzer** [comment]
Implemented as of 3fb4e38a0451ff5a998fc71df108a63d7151bd8d
