### ISSUE TITLE
downloaded the ver 8.16 but it showed the ver 8.15 in the content files

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#91]
Hi Phil,

I downloaded the version 8.16 (https://github.com/eugenemel/maven/releases/tag/8.1.16). When I installed and replaced the previous version 8.15, it said it was done successfully. However, when I opened Maven, it still shows the ver 8.1.15. Would you mind checking it again? or maybe I am the only one had this bug. Thanks!--Ngoc

**Comment by PMSeitzer** [comment]
Hey @ngoccalico, If the version tag is showing `8.1.15` in the header, then that is the version you are using.
Could you try re-installing `8.1.16` again to see if it works?

**Comment by ngoccalico** [comment]
Hi @PMSeitzer, I tried to reinstalled it, yet it still showed the ver 8.1.15 instead of 8.1.16. @cmsand saw the same issue with her installation as well. 
Thanks!

**Comment by PMSeitzer** [comment]
If a previous installation of maven exists on the machine, it helps to rename this installation, and eject any currently mounting maven installation disk images.
