### ISSUE TITLE
Populate candidates in compound widget for mzrollDB files

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#92]
And add an option called `rumsDB` to the drop-down menu, which would read the values from the `mzrollDB` file instead of computing on the fly

See `mass_spec` Issue 212:
https://github.com/calico/mass_spec/issues/212

**Comment by PMSeitzer** [comment]
Color rows where `is_match` == 1 green, and where `is_match` == 0 red (read from `matches` table)

**Comment by PMSeitzer** [comment]
For the time being, no need to implement to consider `is_match` flags for row highlighting (no color coding rows for now)

**Comment by cmsand** [comment]
It would be nice to update the fragmentation widget at the same time as peak groups are selected from the `rumsdb` table.  Currently, the reference compound is not updated when navigating through `rumsdb`-based matches.

**Comment by cmsand** [comment]
Note: for the above, it is possible that renaming this library (by adding a field in the msp file) could allow this to hook into maven

**Comment by PMSeitzer** [comment]
Implemented as of 6a5ca4656251150e01e4738d98b8a97679d3c652
