### ISSUE TITLE
Add quotation marks around compound names in csv export from bookmarks

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#96]
This way, any names that contain commas as a part of the name are kept together when opened in excel.

**Comment by PMSeitzer** [comment]
Implemented as of 8378a0e05c286f086f1582437bd77d1b62ece55f

**Comment by cmsand** [comment]
Hey Phil, still having this issue with Excel delimiting on commas in compound names. 

Using Maven 8.1.16

**Comment by cmsand** [comment]
Might be worth noting that I exported my bookmarks as a csv. Not sure if is matters if I export as tab or csv
