### ISSUE TITLE
Print PDF function for scatterplots font scaling issue

### ISSUE THREAD

**Issue by Calicotobi** [eugenemel/maven#98]
When printing a scatterplot to PDF, the PDF displays buggy fonts for the axis scaling (see screenshot).

![Screen Shot 2019-12-03 at 9 21 41 AM](https://user-images.githubusercontent.com/31489371/70073886-92d2c200-15ae-11ea-8d7a-4af9362ad7e3.png)

**Comment by PMSeitzer** [comment]
Implemented as of f56f886aef0b1fd0bcae870f6cd87dacbf3422d7
